export const ADVANCED_PUZZLES_A = [
  {
    id: "expert_065_024nn",
    title: "엑스레이 퀸 희생",
    prompt: "BLACK: 퀸을 희생해 숨어 있는 비숍의 메이트 라인을 여세요.",
    hint: "Qxg2+ Bxg2 Bxg2#입니다. 퀸 희생이 f3 비숍을 g2로 유인해 b7 비숍의 엑스레이 공격을 엽니다.",
    fen: "2k5/1bp3pp/1p2p3/2n1b3/2P5/Q4BqP/PP1r2P1/4RRBK b - - 0 25",
    playerColor: "b",
    solutionSteps: [["g3g2"], ["f3g2"], ["b7g2"]],
    tags: ["advanced", "sacrifice", "xRayAttack", "mateIn2", "kingsideAttack"],
    source: { provider: "lichess", puzzleId: "024nn", rating: 2314 },
    localized: {
      en: {
        title: "X-Ray Queen Sacrifice",
        prompt: "BLACK: Sacrifice the queen to open the hidden bishop mating line.",
        hint: "Qxg2+ Bxg2 Bxg2#. The queen sacrifice draws the f3 bishop to g2 and opens the b7 bishop's x-ray attack.",
      },
      ja: {
        title: "エックスレイのクイーン犠牲",
        prompt: "BLACK: クイーンを犠牲にして隠れたビショップのメイトラインを開いてください.",
        hint: "Qxg2+ Bxg2 Bxg2#です. クイーン犠牲でf3のビショップをg2へ誘い, b7のビショップのエックスレイ攻撃を開きます.",
      },
    },
  },
  {
    id: "expert_066_0bDMp",
    title: "킹과 룩의 스큐어",
    prompt: "BLACK: 연속 체크로 킹을 몰아내고 뒤의 룩을 잡으세요.",
    hint: "Qh1+ Ke3 Re1+ Kf4 Rxe6입니다. 퀸 체크가 킹을 e파일로 유도하고 룩 체크가 킹과 e6 룩을 스큐어합니다.",
    fen: "k7/1pp5/4R3/5p2/2PQ2P1/1P3K2/P4P1q/6r1 b - - 0 40",
    playerColor: "b",
    solutionSteps: [["h2h1"], ["f3e3"], ["g1e1"], ["e3f4"], ["e1e6"]],
    tags: ["advanced", "skewer", "endgame", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "0bDMp", rating: 2524 },
    localized: {
      en: {
        title: "King and Rook Skewer",
        prompt: "BLACK: Drive the king away with consecutive checks and take the rook behind it.",
        hint: "Qh1+ Ke3 Re1+ Kf4 Rxe6. The queen check draws the king onto the e-file, where the rook check skewers the king and rook on e6.",
      },
      ja: {
        title: "キングとルークの串刺し",
        prompt: "BLACK: 連続チェックでキングを追い払い, 後ろのルークを取ってください.",
        hint: "Qh1+ Ke3 Re1+ Kf4 Rxe6です. クイーンチェックでキングをeファイルへ誘い, ルークチェックでキングとe6のルークを串刺しにします.",
      },
    },
  },
  {
    id: "expert_067_0QpJl",
    title: "디플렉션 연쇄 전술",
    prompt: "BLACK: 나이트 체크로 퀸을 유인한 뒤 두 룩을 차례로 제거하세요.",
    hint: "Ng3+ Qxg3 Rxf1+ Kg2 Rf5 Rxf5 Qxf5입니다. 나이트가 퀸을 빗나가게 하고 룩 체크와 스큐어가 두 번째 룩도 퀸 앞에 유인합니다.",
    fen: "8/1p3rpk/p1p4p/1PP1Rnq1/P7/8/5Q1P/5R1K b - - 6 39",
    playerColor: "b",
    solutionSteps: [["f5g3"], ["f2g3"], ["f7f1"], ["h1g2"], ["f1f5"], ["e5f5"], ["g5f5"]],
    tags: ["advanced", "deflection", "skewer", "discoveredAttack", "endgame"],
    source: { provider: "lichess", puzzleId: "0QpJl", rating: 2702 },
    localized: {
      en: {
        title: "Deflection Chain",
        prompt: "BLACK: Deflect the queen with a knight check, then remove both rooks in sequence.",
        hint: "Ng3+ Qxg3 Rxf1+ Kg2 Rf5 Rxf5 Qxf5. The knight deflects the queen, and the rook check and skewer draw the second rook onto a queen capture.",
      },
      ja: {
        title: "連続するそらし",
        prompt: "BLACK: ナイトチェックでクイーンをそらし, 2つのルークを順番に取り除いてください.",
        hint: "Ng3+ Qxg3 Rxf1+ Kg2 Rf5 Rxf5 Qxf5です. ナイトがクイーンをそらし, ルークチェックと串刺しで2つ目のルークもクイーンの捕獲地点へ誘います.",
      },
    },
  },
  {
    id: "expert_068_0iunX",
    title: "클리어런스 퀸 포크",
    prompt: "BLACK: 룩 체크로 퀸의 길을 비우고 킹과 룩을 포크하세요.",
    hint: "Rg4+ Kh1 Qf4 Qe2 Qe4+ f3 Qxc6입니다. 룩이 f4를 비운 뒤 퀸이 e4에서 킹과 c6 룩을 포크합니다.",
    fen: "1q2r2k/6bp/1PR3p1/P7/5r2/4B3/2Q2P1P/4R1K1 b - - 0 34",
    playerColor: "b",
    solutionSteps: [["f4g4"], ["g1h1"], ["b8f4"], ["c2e2"], ["f4e4"], ["f2f3"], ["e4c6"]],
    tags: ["advanced", "clearance", "fork", "pin", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "0iunX", rating: 2697 },
    localized: {
      en: {
        title: "Clearance Queen Fork",
        prompt: "BLACK: Clear the queen's route with a rook check, then fork the king and rook.",
        hint: "Rg4+ Kh1 Qf4 Qe2 Qe4+ f3 Qxc6. The rook vacates f4, allowing the queen to fork the king and c6 rook from e4.",
      },
      ja: {
        title: "クリアランスのクイーンフォーク",
        prompt: "BLACK: ルークチェックでクイーンの経路を空け, キングとルークをフォークしてください.",
        hint: "Rg4+ Kh1 Qf4 Qe2 Qe4+ f3 Qxc6です. ルークがf4を空け, クイーンがe4からキングとc6のルークをフォークします.",
      },
    },
  },
  {
    id: "expert_069_08aqk",
    title: "희생으로 만든 퀸 스큐어",
    prompt: "BLACK: 룩을 희생해 백 퀸을 끌어낸 뒤 체크로 킹과 퀸을 꿰뚫으세요.",
    hint: "Rh1 Qxh1 Qb1+ Kd2 Qxh1입니다. 룩 희생이 퀸을 h1에 놓고 Qb1+가 킹을 몰아내며 퀸을 스큐어합니다.",
    fen: "1k4r1/pp6/6q1/4P3/2Pp4/1P3RP1/P3R2r/4KQ2 b - - 7 36",
    playerColor: "b",
    solutionSteps: [["h2h1"], ["f1h1"], ["g6b1"], ["e1d2"], ["b1h1"]],
    tags: ["advanced", "sacrifice", "skewer", "pin", "exposedKing"],
    source: { provider: "lichess", puzzleId: "08aqk", rating: 2696 },
    localized: {
      en: {
        title: "Queen Skewer by Sacrifice",
        prompt: "BLACK: Sacrifice the rook to draw out the white queen, then skewer king and queen with check.",
        hint: "Rh1 Qxh1 Qb1+ Kd2 Qxh1. The rook sacrifice places the queen on h1, and Qb1+ drives away the king before taking the skewered queen.",
      },
      ja: {
        title: "犠牲で作るクイーンの串刺し",
        prompt: "BLACK: ルークを犠牲にして白クイーンを誘い出し, チェックでキングとクイーンを串刺しにしてください.",
        hint: "Rh1 Qxh1 Qb1+ Kd2 Qxh1です. ルーク犠牲でクイーンをh1へ置き, Qb1+でキングを追ってから串刺しのクイーンを取ります.",
      },
    },
  },
  {
    id: "expert_070_0JBkb",
    title: "디스커버드 체크 추격",
    prompt: "WHITE: 비숍을 비켜 룩 체크를 열고 킹을 몰아 수비 룩을 제거하세요.",
    hint: "Bd1+ Ke7 Qg7+ Kd6 Rxf8 Qe7 Qe5+입니다. Bd1+가 f파일 룩의 디스커버드 체크를 열고 연속 체크가 f8 룩의 수비를 무너뜨립니다.",
    fen: "3q1r2/1p3k2/4p3/p2p4/3P2QP/4bBP1/1P4K1/2r2R2 w - - 2 28",
    playerColor: "w",
    solutionSteps: [["f3d1"], ["f7e7"], ["g4g7"], ["e7d6"], ["f1f8"], ["d8e7"], ["g7e5"]],
    tags: ["advanced", "deflection", "discoveredCheck", "discoveredAttack", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "0JBkb", rating: 2699 },
    localized: {
      en: {
        title: "Discovered-Check Pursuit",
        prompt: "WHITE: Move the bishop aside to uncover a rook check, then chase the king and remove the defending rook.",
        hint: "Bd1+ Ke7 Qg7+ Kd6 Rxf8 Qe7 Qe5+. Bd1+ uncovers the f-file rook check, and the forcing chase breaks the defense of the f8 rook.",
      },
      ja: {
        title: "ディスカバードチェックの追撃",
        prompt: "WHITE: ビショップを動かしてルークチェックを開き, キングを追って守備のルークを取り除いてください.",
        hint: "Bd1+ Ke7 Qg7+ Kd6 Rxf8 Qe7 Qe5+です. Bd1+でfファイルのルークによるディスカバードチェックを開き, 連続チェックでf8のルークの守備を崩します.",
      },
    },
  },
  {
    id: "expert_071_0B4Hl",
    title: "중간 체크로 여는 폰 메이트",
    prompt: "BLACK: 연속 폰 희생 사이에 나이트 체크를 끼워 넣어 메이트하세요.",
    hint: "b3+ axb3 Nb4+ cxb4 cxb3#입니다. Nb4+ 중간 수가 c3 폰을 b4로 유인해 c4 폰의 메이트 포획을 엽니다.",
    fen: "r3k1nr/p4p1p/b1n5/3pPN2/1ppP2p1/2P1q1P1/PPK1B1P1/RN1Q1R2 b kq - 3 18",
    playerColor: "b",
    solutionSteps: [["b4b3"], ["a2b3"], ["c6b4"], ["c3b4"], ["c4b3"]],
    tags: ["advanced", "sacrifice", "intermezzo", "mateIn3", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "0B4Hl", rating: 2660 },
    localized: {
      en: {
        title: "Pawn Mate with an Intermezzo",
        prompt: "BLACK: Insert a knight check between pawn sacrifices and force mate.",
        hint: "b3+ axb3 Nb4+ cxb4 cxb3#. The Nb4+ intermezzo draws the c3 pawn to b4 and opens the c4 pawn's mating capture.",
      },
      ja: {
        title: "中間チェックで開くポーンメイト",
        prompt: "BLACK: ポーン犠牲の間にナイトチェックを挟み, メイトを決めてください.",
        hint: "b3+ axb3 Nb4+ cxb4 cxb3#です. Nb4+の中間手がc3のポーンをb4へ誘い, c4のポーンによるメイトの取りを開きます.",
      },
    },
  },
  {
    id: "expert_072_0jDa5",
    title: "비숍 간섭과 룩 침투",
    prompt: "BLACK: 비숍 희생으로 나이트를 유인하고 체크를 이어 룩을 획득하세요.",
    hint: "Bg5+ Nxg5 Rxd4+ Ke1 Qxb1+입니다. Bg5+가 나이트를 수비선에서 떼어 놓는 간섭과 디플렉션으로 d파일 침투를 가능하게 합니다.",
    fen: "2br1k2/p1p2ppQ/1pB1pb1p/8/3P4/5N2/1qPK1PPP/1R5R b - - 3 19",
    playerColor: "b",
    solutionSteps: [["f6g5"], ["f3g5"], ["d8d4"], ["d2e1"], ["b2b1"]],
    tags: ["advanced", "sacrifice", "deflection", "interference", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "0jDa5", rating: 2652 },
    localized: {
      en: {
        title: "Bishop Interference and Rook Invasion",
        prompt: "BLACK: Sacrifice the bishop to draw off the knight, then continue checking and win the rook.",
        hint: "Bg5+ Nxg5 Rxd4+ Ke1 Qxb1+. Bg5+ interferes with the defense and deflects the knight, enabling the invasion down the d-file.",
      },
      ja: {
        title: "ビショップの干渉とルーク侵入",
        prompt: "BLACK: ビショップを犠牲にしてナイトを誘い, チェックを続けてルークを獲得してください.",
        hint: "Bg5+ Nxg5 Rxd4+ Ke1 Qxb1+です. Bg5+が守備に干渉してナイトをそらし, dファイルへの侵入を可能にします.",
      },
    },
  },
  {
    id: "expert_073_0kzBy",
    title: "킹 유인과 룩 침투",
    prompt: "BLACK: 나이트를 희생해 킹을 끌어낸 뒤 룩과 퀸으로 추격하세요.",
    hint: "Nxf2 Kxf2 Rd2+ Kf1 Rd1+ Kg2 Qb2+입니다. 나이트 희생이 킹을 f2로 유인해 룩의 2랭크와 1랭크 침투를 엽니다.",
    fen: "3r4/p1p2pk1/1p3qp1/8/2P1Q1n1/1P2PNP1/P4PK1/7R b - - 5 24",
    playerColor: "b",
    solutionSteps: [["g4f2"], ["g2f2"], ["d8d2"], ["f2f1"], ["d2d1"], ["f1g2"], ["f6b2"]],
    tags: ["advanced", "sacrifice", "attraction", "pin", "endgame"],
    source: { provider: "lichess", puzzleId: "0kzBy", rating: 2647 },
    localized: {
      en: {
        title: "King Attraction and Rook Invasion",
        prompt: "BLACK: Sacrifice the knight to draw out the king, then pursue it with rook and queen.",
        hint: "Nxf2 Kxf2 Rd2+ Kf1 Rd1+ Kg2 Qb2+. The knight sacrifice attracts the king to f2 and opens the second and first ranks for the rook invasion.",
      },
      ja: {
        title: "キング誘引とルーク侵入",
        prompt: "BLACK: ナイトを犠牲にしてキングを誘い出し, ルークとクイーンで追撃してください.",
        hint: "Nxf2 Kxf2 Rd2+ Kf1 Rd1+ Kg2 Qb2+です. ナイト犠牲がキングをf2へ誘い, ルークの2段目と1段目への侵入を開きます.",
      },
    },
  },
  {
    id: "expert_074_0PcEZ",
    title: "나이트 희생 비숍 포크",
    prompt: "BLACK: 나이트를 내주고 비숍을 침투시켜 킹과 룩을 포크하세요.",
    hint: "Bxb2 Bxd5 Bc3+ Bd2 Bxd2+입니다. d5 나이트 희생이 비숍의 c3 침투 시간을 벌고, 체크 포크가 e1 킹과 a1 룩을 동시에 노립니다.",
    fen: "r4rk1/p1p4p/3qp1p1/3nb3/2B3Q1/4P3/PP3PPP/R1B1K2R b KQ - 1 16",
    playerColor: "b",
    solutionSteps: [["e5b2"], ["c4d5"], ["b2c3"], ["c1d2"], ["c3d2"]],
    tags: ["advanced", "sacrifice", "fork", "middlegame", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "0PcEZ", rating: 2636 },
    localized: {
      en: {
        title: "Knight Sacrifice Bishop Fork",
        prompt: "BLACK: Give up the knight and invade with the bishop to fork king and rook.",
        hint: "Bxb2 Bxd5 Bc3+ Bd2 Bxd2+. Sacrificing the d5 knight gains time for the bishop to reach c3, where its checking fork attacks the e1 king and a1 rook.",
      },
      ja: {
        title: "ナイト犠牲のビショップフォーク",
        prompt: "BLACK: ナイトを差し出し, ビショップを侵入させてキングとルークをフォークしてください.",
        hint: "Bxb2 Bxd5 Bc3+ Bd2 Bxd2+です. d5のナイト犠牲がビショップをc3へ運ぶ時間を作り, チェックフォークでe1のキングとa1のルークを同時に狙います.",
      },
    },
  },
  {
    id: "expert_075_0KfyN",
    title: "퀸 메이트를 위한 이중 희생",
    prompt: "WHITE: 비숍과 룩을 연속 희생해 퀸의 메이트 길을 여세요.",
    hint: "Bb7+ Kxb7 Rxb6+ axb6 Qc7+ Ka6 Qxb6#입니다. 두 희생이 킹을 끌어내고 b6를 비워 퀸의 메이트 경로를 만듭니다.",
    fen: "k2r1r2/p5p1/BpR5/3p1qn1/N2P2b1/P3P1B1/1P5P/2Q3K1 w - - 7 30",
    playerColor: "w",
    solutionSteps: [["a6b7"], ["a8b7"], ["c6b6"], ["a7b6"], ["c1c7"], ["b7a6"], ["c7b6"]],
    tags: ["advanced", "sacrifice", "attraction", "clearance", "mateIn4"],
    source: { provider: "lichess", puzzleId: "0KfyN", rating: 2628 },
    localized: {
      en: {
        title: "Double Sacrifice for the Queen Mate",
        prompt: "WHITE: Sacrifice bishop and rook in sequence to clear the queen's mating route.",
        hint: "Bb7+ Kxb7 Rxb6+ axb6 Qc7+ Ka6 Qxb6#. The two sacrifices attract the king and clear b6 for the queen's mating route.",
      },
      ja: {
        title: "クイーンメイトへの二重犠牲",
        prompt: "WHITE: ビショップとルークを連続で犠牲にし, クイーンのメイト経路を開いてください.",
        hint: "Bb7+ Kxb7 Rxb6+ axb6 Qc7+ Ka6 Qxb6#です. 2つの犠牲でキングを誘い出し, b6を空けてクイーンのメイト経路を作ります.",
      },
    },
  },
  {
    id: "expert_076_0fs1z",
    title: "h파일 클리어런스 메이트",
    prompt: "WHITE: 폰과 룩을 희생해 다른 룩의 h파일 메이트를 여세요.",
    hint: "h7+ Kxh7 Rf7+ Rxf7 Rh1+ Kg8 Rh8#입니다. 연속 희생이 h파일을 비우고 킹을 h8 메이트 칸으로 되돌립니다.",
    fen: "5rk1/8/2P3pP/3pB1P1/2nP4/1b6/rb6/1K2RR2 w - - 0 36",
    playerColor: "w",
    solutionSteps: [["h6h7"], ["g8h7"], ["f1f7"], ["f8f7"], ["e1h1"], ["h7g8"], ["h1h8"]],
    tags: ["advanced", "sacrifice", "attraction", "clearance", "mateIn4"],
    source: { provider: "lichess", puzzleId: "0fs1z", rating: 2626 },
    localized: {
      en: {
        title: "H-File Clearance Mate",
        prompt: "WHITE: Sacrifice the pawn and rook to open an h-file mate for the other rook.",
        hint: "h7+ Kxh7 Rf7+ Rxf7 Rh1+ Kg8 Rh8#. The consecutive sacrifices clear the h-file and return the king to the h8 mating square.",
      },
      ja: {
        title: "hファイルのクリアランスメイト",
        prompt: "WHITE: ポーンとルークを犠牲にして, もう1つのルークによるhファイルのメイトを開いてください.",
        hint: "h7+ Kxh7 Rf7+ Rxf7 Rh1+ Kg8 Rh8#です. 連続犠牲がhファイルを空け, キングをh8のメイト地点へ戻します.",
      },
    },
  },
  {
    id: "expert_077_1Di98",
    title: "나이트 희생 간섭 전술",
    prompt: "BLACK: 나이트 희생과 비숍 체크를 이어 킹의 수비를 흔들고 룩을 잡으세요.",
    hint: "Ne4+ Bxe4 Bg3+ Kf1 Qxh1+입니다. 나이트 희생이 비숍을 e4로 유인하고 Bg3+가 킹의 대응을 방해해 퀸이 h1 룩을 체크로 잡습니다.",
    fen: "r3k3/1pb2pp1/p1n1pn2/3p2P1/3P4/4BB1r/PPP1NKPq/R2Q3R b q - 1 18",
    playerColor: "b",
    solutionSteps: [["f6e4"], ["f3e4"], ["c7g3"], ["f2f1"], ["h2h1"]],
    tags: ["advanced", "sacrifice", "interference", "pin", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "1Di98", rating: 2624 },
    localized: {
      en: {
        title: "Knight Sacrifice Interference",
        prompt: "BLACK: Combine a knight sacrifice and bishop check to disrupt the king's defense and take the rook.",
        hint: "Ne4+ Bxe4 Bg3+ Kf1 Qxh1+. The knight sacrifice draws the bishop to e4, and Bg3+ interferes with the king's defense so the queen takes the h1 rook with check.",
      },
      ja: {
        title: "ナイト犠牲の干渉戦術",
        prompt: "BLACK: ナイト犠牲とビショップチェックを組み合わせ, キングの守備を乱してルークを取ってください.",
        hint: "Ne4+ Bxe4 Bg3+ Kf1 Qxh1+です. ナイト犠牲がビショップをe4へ誘い, Bg3+がキングの守備を妨げてクイーンがh1のルークをチェックで取ります.",
      },
    },
  },
  {
    id: "expert_078_03BKg",
    title: "퀸 희생 뒤 중간 체크",
    prompt: "WHITE: 퀸을 희생한 뒤 비숍 체크를 끼워 넣어 나이트 메이트를 완성하세요.",
    hint: "Qxf6+ gxf6 Bh6+ Kg8 Nxf6#입니다. Bh6+ 중간 체크가 킹을 g8에 고정해 나이트의 메이트 칸을 확보합니다.",
    fen: "1rbq1k1r/p1p1n1pp/3bPpn1/3N4/3P4/2P2Q2/PP3PPP/R1B1R1K1 w - - 3 19",
    playerColor: "w",
    solutionSteps: [["f3f6"], ["g7f6"], ["c1h6"], ["f8g8"], ["d5f6"]],
    tags: ["advanced", "sacrifice", "intermezzo", "mateIn3", "forcingCheck"],
    source: { provider: "lichess", puzzleId: "03BKg", rating: 2569 },
    localized: {
      en: {
        title: "Intermezzo after the Queen Sacrifice",
        prompt: "WHITE: Sacrifice the queen, insert a bishop check, and complete the knight mate.",
        hint: "Qxf6+ gxf6 Bh6+ Kg8 Nxf6#. The Bh6+ intermezzo fixes the king on g8 and secures the knight's mating square.",
      },
      ja: {
        title: "クイーン犠牲後の中間チェック",
        prompt: "WHITE: クイーンを犠牲にしたあとビショップチェックを挟み, ナイトメイトを完成してください.",
        hint: "Qxf6+ gxf6 Bh6+ Kg8 Nxf6#です. Bh6+の中間チェックがキングをg8に固定し, ナイトのメイト地点を確保します.",
      },
    },
  },
  {
    id: "expert_079_18SBf",
    title: "나이트 디플렉션 메이트",
    prompt: "WHITE: 룩을 희생해 수비 나이트를 유인하고 다른 나이트로 메이트하세요.",
    hint: "Rd7+ Nxd7 Qe6+ Kf8 Nxd7#입니다. 룩 희생이 b8 나이트를 d7로 끌어내 수비를 무너뜨리고 메이트 표적으로 만듭니다.",
    fen: "rn1Rn2r/1p2k1pp/p7/2N1pQ2/4P3/8/PPq3PP/6K1 w - - 0 22",
    playerColor: "w",
    solutionSteps: [["d8d7"], ["b8d7"], ["f5e6"], ["e7f8"], ["c5d7"]],
    tags: ["advanced", "sacrifice", "deflection", "mateIn3", "cornerMate"],
    source: { provider: "lichess", puzzleId: "18SBf", rating: 2491 },
    localized: {
      en: {
        title: "Knight Deflection Mate",
        prompt: "WHITE: Sacrifice the rook to deflect the defending knight, then mate with the other knight.",
        hint: "Rd7+ Nxd7 Qe6+ Kf8 Nxd7#. The rook sacrifice draws the b8 knight to d7, breaking its defense and making it the final mating target.",
      },
      ja: {
        title: "ナイトをそらすメイト",
        prompt: "WHITE: ルークを犠牲にして守備のナイトをそらし, もう1つのナイトでメイトしてください.",
        hint: "Rd7+ Nxd7 Qe6+ Kf8 Nxd7#です. ルーク犠牲がb8のナイトをd7へ誘い, 守備を崩して最後のメイトの標的にします.",
      },
    },
  },
  {
    id: "expert_080_01A5W",
    title: "더블 체크 중간 수",
    prompt: "WHITE: 룩을 희생하고 연속 체크를 끼워 넣어 침투한 룩을 되찾으세요.",
    hint: "Rxg6+ fxg6 f7+ Kxf7 fxg6+ Ke7 Qxe2+입니다. 룩 희생 뒤 f7+ 더블 체크와 중간 체크가 킹을 유인해 e2 룩을 회수할 시간을 법니다.",
    fen: "4r1k1/pp3p2/3p1Ppq/5P2/8/6RP/PP2rQ2/6RK w - - 3 40",
    playerColor: "w",
    solutionSteps: [["g3g6"], ["f7g6"], ["f6f7"], ["g8f7"], ["f5g6"], ["f7e7"], ["f2e2"]],
    tags: ["advanced", "sacrifice", "attraction", "doubleCheck", "discoveredCheck", "interference", "intermezzo"],
    source: { provider: "lichess", puzzleId: "01A5W", rating: 2359 },
    localized: {
      en: {
        title: "Double-Check Intermezzo",
        prompt: "WHITE: Sacrifice the rook and insert consecutive checks to recover the invading rook.",
        hint: "Rxg6+ fxg6 f7+ Kxf7 fxg6+ Ke7 Qxe2+. After the rook sacrifice, the f7+ double check and intermezzo checks attract the king and gain time to recover the e2 rook.",
      },
      ja: {
        title: "ダブルチェックの中間手",
        prompt: "WHITE: ルークを犠牲にして連続チェックを挟み, 侵入したルークを取り返してください.",
        hint: "Rxg6+ fxg6 f7+ Kxf7 fxg6+ Ke7 Qxe2+です. ルーク犠牲後のf7+のダブルチェックと中間チェックがキングを誘い, e2のルークを取る時間を作ります.",
      },
    },
  },
  {
    id: "expert_081_1A8Xe",
    title: "더블 체크 룩 메이트",
    prompt: "BLACK: 비숍을 움직여 두 기물의 동시 체크를 만들고 룩으로 끝내세요.",
    hint: "Bg3+ Kg1 Re1#입니다. 비숍이 직접 체크하면서 e2 룩의 가로선을 열어 더블 체크를 만들고 킹 이동 뒤 메이트합니다.",
    fen: "8/7R/6p1/6kp/7n/1B3P1P/P1R1rb1K/8 b - - 4 36",
    playerColor: "b",
    solutionSteps: [["f2g3"], ["h2g1"], ["e2e1"]],
    tags: ["advanced", "doubleCheck", "discoveredCheck", "mateIn2", "pillsburysMate"],
    source: { provider: "lichess", puzzleId: "1A8Xe", rating: 2324 },
    localized: {
      en: {
        title: "Double Check Rook Mate",
        prompt: "BLACK: Move the bishop to check with two pieces at once, then finish with the rook.",
        hint: "Bg3+ Kg1 Re1#. The bishop checks directly while uncovering the e2 rook across the rank, creating double check before the rook mate.",
      },
      ja: {
        title: "ダブルチェックのルークメイト",
        prompt: "BLACK: ビショップを動かして2つの駒で同時にチェックし, ルークで仕留めてください.",
        hint: "Bg3+ Kg1 Re1#です. ビショップが直接チェックしながらe2のルークの横線を開き, ダブルチェックのあとルークでメイトします.",
      },
    },
  },
  {
    id: "expert_082_0CMCY",
    title: "엑스레이 대각선 메이트",
    prompt: "WHITE: 연속 체크로 대각선을 비우고 퀸의 엑스레이 메이트를 완성하세요.",
    hint: "Qa8+ Kd7 Bxb5+ c6 Bxc6+ bxc6 Qxc6#입니다. 비숍 교환이 a8-c6 대각선을 차례로 비워 퀸의 엑스레이 공격을 메이트로 바꿉니다.",
    fen: "2kr3r/1pp1q1b1/3p1n1p/1p1Pp1p1/2B1PpbP/Q7/PPPB2P1/2K1R2R w - - 0 17",
    playerColor: "w",
    solutionSteps: [["a3a8"], ["c8d7"], ["c4b5"], ["c7c6"], ["b5c6"], ["b7c6"], ["a8c6"]],
    tags: ["advanced", "xRayAttack", "intermezzo", "mateIn4", "queensideAttack"],
    source: { provider: "lichess", puzzleId: "0CMCY", rating: 2329 },
    localized: {
      en: {
        title: "X-Ray Diagonal Mate",
        prompt: "WHITE: Clear the diagonal with consecutive checks and complete the queen's x-ray mate.",
        hint: "Qa8+ Kd7 Bxb5+ c6 Bxc6+ bxc6 Qxc6#. The bishop exchanges progressively clear the a8-c6 diagonal and turn the queen's x-ray attack into mate.",
      },
      ja: {
        title: "エックスレイ対角線のメイト",
        prompt: "WHITE: 連続チェックで対角線を空け, クイーンのエックスレイメイトを完成してください.",
        hint: "Qa8+ Kd7 Bxb5+ c6 Bxc6+ bxc6 Qxc6#です. ビショップ交換がa8-c6の対角線を順番に空け, クイーンのエックスレイ攻撃をメイトへ変えます.",
      },
    },
  },
];
