import {
  getClearedPuzzleIds,
  isPuzzleCleared,
  markPuzzleCleared,
  PUZZLE_PROGRESS_KEY,
} from "./playerState.js?v=20260715-mobile09";

export {
  getClearedPuzzleIds,
  isPuzzleCleared,
  markPuzzleCleared,
  PUZZLE_PROGRESS_KEY,
};

export const PUZZLES = [
  {
    id: "mate_scholar",
    title: "첫 번째 체크메이트",
    prompt: "WHITE: 약한 f7 칸을 노려 한 수로 끝내세요.",
    hint: "퀸이 f7로 들어가면 왕이 도망갈 곳이 없습니다.",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    playerColor: "w",
    solutionSteps: [["h5f7"]],
    tags: ["mate-in-1", "beginner"],
  },
  {
    id: "fools_mate",
    title: "가장 빠른 메이트",
    prompt: "BLACK: 열린 대각선을 이용해 즉시 체크메이트하세요.",
    hint: "흑 퀸이 h4로 가면 백 왕은 막을 수 없습니다.",
    fen: "rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2",
    playerColor: "b",
    solutionSteps: [["d8h4"]],
    tags: ["mate-in-1", "beginner"],
  },
  {
    id: "back_rank_mate",
    title: "백랭크 메이트",
    prompt: "WHITE: 룩으로 마지막 줄의 왕을 가둬보세요.",
    hint: "상대 폰들이 왕의 탈출 칸을 막고 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/6PP/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e8"]],
    tags: ["mate-in-1", "rook"],
  },
  {
    id: "rook_takes_queen",
    title: "공짜 퀸",
    prompt: "WHITE: 일직선으로 열린 길을 보고 가장 큰 기물을 잡으세요.",
    hint: "e파일 위에 룩이 지나갈 길이 비어 있습니다.",
    fen: "6k1/4qppp/8/8/8/8/6PP/3QR1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e7"]],
    tags: ["capture", "rook"],
  },
  {
    id: "answer_check",
    title: "체크를 해결하며 이득 보기",
    prompt: "WHITE: 체크를 막으면서 상대 퀸을 잡으세요.",
    hint: "퀸이나 룩으로 e2 칸을 잡을 수 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/4q1PP/3QR1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1e2", "e1e2"]],
    tags: ["check", "capture"],
  },
  {
    id: "knight_fork",
    title: "나이트 포크",
    prompt: "WHITE: 나이트로 체크를 걸며 퀸을 잡으세요.",
    hint: "나이트는 직선이 아니라 뛰어넘어 공격합니다.",
    fen: "r5k1/4qppp/8/3N4/8/8/6PP/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d5e7"]],
    tags: ["fork", "knight"],
  },
  {
    id: "castle_safe",
    title: "킹을 안전하게",
    prompt: "WHITE: 캐슬링으로 킹을 피신시키세요.",
    hint: "킹을 두 칸 오른쪽으로 움직이면 짧은 캐슬링입니다.",
    fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
    playerColor: "w",
    solutionSteps: [["e1g1"]],
    tags: ["rule", "castle"],
  },
  {
    id: "promotion_queen",
    title: "승급",
    prompt: "WHITE: 폰을 끝까지 전진시켜 퀸으로 승급하세요.",
    hint: "a폰을 a8까지 올리고 퀸을 선택합니다.",
    fen: "7k/P7/8/8/8/8/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a7a8q"]],
    tags: ["rule", "promotion"],
  },
  {
    id: "rook_file_mate",
    title: "열린 파일 메이트",
    prompt: "WHITE: 룩을 마지막 줄까지 올려 왕을 가두세요.",
    hint: "a파일이 완전히 열려 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/6PP/R5K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a1a8"]],
    tags: ["mate-in-1", "rook"],
  },
  {
    id: "black_back_rank",
    title: "퀸의 백랭크 메이트",
    prompt: "BLACK: 퀸을 첫째 줄에 침투시켜 갇힌 백 킹을 메이트하세요.",
    hint: "Qd1#이면 세 폰이 킹의 앞칸을 막고 퀸이 양옆 탈출 칸을 모두 장악합니다.",
    fen: "6k1/8/8/8/8/3q4/5PPP/6K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["d3d1"]],
    tags: ["mate-in-1", "queen", "back-rank"],
  },
  {
    id: "bishop_takes_queen",
    title: "비숍의 대각선",
    prompt: "WHITE: 대각선 위의 가장 큰 기물을 잡으세요.",
    hint: "비숍은 c4에서 d5를 공격합니다.",
    fen: "6k1/5ppp/8/3q4/2B5/8/6PP/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4d5"]],
    tags: ["capture", "bishop"],
  },
  {
    id: "black_promotion",
    title: "흑의 나이트 언더프로모션 포크",
    prompt: "BLACK: 폰을 나이트로 승급해 킹과 퀸을 동시에 공격하세요.",
    hint: "c1=N+은 e2의 킹을 체크하면서 b3의 퀸도 공격합니다.",
    fen: "7k/8/8/8/8/1Q6/2p1K3/8 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["c2c1n"]],
    tags: ["promotion", "underpromotion", "fork", "knight", "check"],
  },
  {
    id: "queen_takes_rook",
    title: "퀸으로 룩 잡기",
    prompt: "WHITE: 체크를 해결하면서 룩을 잡으세요.",
    hint: "퀸이 e2 칸으로 이동할 수 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/4r1PP/3Q2K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1e2"]],
    tags: ["check", "capture"],
  },
  {
    id: "knight_takes_rook",
    title: "나이트의 반격",
    prompt: "WHITE: 나이트로 공격받는 기물을 잡으세요.",
    hint: "나이트는 d4에서 e2로 점프할 수 있습니다.",
    fen: "6k1/5ppp/8/8/3N4/8/4r1PP/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d4e2"]],
    tags: ["knight", "capture"],
  },
  {
    id: "rook_defense",
    title: "룩으로 체크 해제",
    prompt: "WHITE: 체크를 막으며 상대 룩을 제거하세요.",
    hint: "같은 파일 위의 룩으로 e2 칸을 잡으세요.",
    fen: "6k1/5ppp/8/8/8/8/4r1PP/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e2"]],
    tags: ["check", "rook"],
  },
  {
    id: "black_queen_capture",
    title: "흑 퀸의 반격",
    prompt: "BLACK: 체크를 해결하면서 백 퀸을 잡으세요.",
    hint: "흑 퀸이 e2 칸으로 이동할 수 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/4Q1PP/3q2K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["d1e2"]],
    tags: ["check", "capture"],
  },
  {
    id: "en_passant",
    title: "앙파상",
    prompt: "WHITE: 방금 두 칸 전진한 흑 폰을 특별한 방법으로 잡으세요.",
    hint: "e5의 폰을 d6으로 대각선 이동해 흑 폰을 잡습니다.",
    fen: "7k/8/8/3pP3/8/8/8/7K w - d6 0 1",
    playerColor: "w",
    solutionSteps: [["e5d6"]],
    tags: ["rule", "en-passant"],
  },
  {
    id: "smothered_mate",
    title: "스머더드 메이트",
    prompt: "WHITE: 자기 기물에 둘러싸인 왕을 나이트로 체크메이트하세요.",
    hint: "e5의 나이트가 f7로 가면 흑 왕의 모든 탈출 칸이 막힙니다.",
    fen: "6rk/6pp/8/4N3/8/8/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e5f7"]],
    tags: ["mate-in-1", "knight"],
  },
  {
    id: "pin_knight",
    title: "움직일 수 없는 나이트",
    prompt: "WHITE: 비숍으로 나이트를 킹 앞에 고정하세요.",
    hint: "비숍을 b5에 놓으면 나이트 뒤에 흑 킹이 있습니다.",
    fen: "4k3/8/2n5/8/2B5/8/8/4K3 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4b5"]],
    tags: ["pin", "bishop"],
  },
  {
    id: "bishop_skewer",
    title: "비숍 스큐어",
    prompt: "WHITE: 킹을 먼저 공격해 뒤에 있는 룩을 노리세요.",
    hint: "비숍을 b4로 옮기면 킹과 룩이 한 대각선에 놓입니다.",
    fen: "8/4r3/3k4/8/8/2B5/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c3b4"]],
    tags: ["skewer", "bishop"],
  },
  {
    id: "queen_double_attack",
    title: "퀸의 더블 어택",
    prompt: "WHITE: 체크를 걸면서 동시에 룩도 공격하세요.",
    hint: "퀸을 h5에 놓으면 킹과 h8의 룩을 함께 노립니다.",
    fen: "4k2r/8/8/8/8/8/8/3QK3 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1h5"]],
    tags: ["double-attack", "queen"],
  },
  {
    id: "discovered_check",
    title: "디스커버드 체크",
    prompt: "WHITE: 비숍을 움직여 뒤에 있던 룩의 공격길을 여세요.",
    hint: "e4의 비숍을 b7로 옮기면 e파일의 룩이 킹을 공격합니다.",
    fen: "4k3/8/8/8/4B3/8/8/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e4b7"]],
    tags: ["discovered-check", "rook"],
  },
  {
    id: "knight_underpromotion",
    title: "나이트 언더프로모션",
    prompt: "WHITE: 폰을 나이트로 승급해 즉시 체크하세요.",
    hint: "e8에서 퀸이 아닌 나이트를 선택해야 킹을 공격합니다.",
    fen: "8/4P1k1/8/8/8/8/8/K7 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e7e8n"]],
    tags: ["underpromotion", "knight"],
  },
  {
    id: "black_castle_long",
    title: "체크가 되는 긴 캐슬링",
    prompt: "BLACK: 긴 캐슬링으로 킹을 옮기는 동시에 룩 체크를 여세요.",
    hint: "O-O-O+를 하면 킹은 c8, 룩은 d8로 이동해 d1의 백 킹을 체크합니다.",
    fen: "r3k3/8/8/8/8/8/8/3K4 b q - 0 1",
    playerColor: "b",
    solutionSteps: [["e8c8"]],
    tags: ["castle", "rook-activation", "check"],
  },
  {
    id: "royal_family_fork",
    title: "왕실 포크",
    prompt: "WHITE: 나이트 한 수로 퀸과 룩을 동시에 공격하세요.",
    hint: "e5의 나이트가 c6으로 가면 두 큰 기물을 함께 노립니다.",
    fen: "1r1q2k1/8/8/4N3/8/8/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e5c6"]],
    tags: ["fork", "knight"],
    localized: {
      en: { title: "Royal Family Fork", prompt: "WHITE: Attack the queen and rook with one knight move.", hint: "Move the knight from e5 to c6 to fork both major pieces." },
      ja: { title: "ロイヤルフォーク", prompt: "WHITE: ナイトの一手でクイーンとルークを同時に攻撃してください。", hint: "e5のナイトをc6へ動かすと、2つの大駒を同時に狙えます。" },
    },
  },
  {
    id: "black_knight_double_attack",
    title: "흑 나이트의 더블 어택",
    prompt: "BLACK: 체크와 동시에 백 퀸을 공격하세요.",
    hint: "e5의 나이트가 c4로 가면 킹과 b2의 퀸을 함께 노립니다.",
    fen: "8/7k/8/4n3/8/8/1Q1K4/8 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["e5c4"]],
    tags: ["fork", "knight", "check"],
    localized: {
      en: { title: "Black Knight Double Attack", prompt: "BLACK: Give check while attacking the white queen.", hint: "Nc4+ attacks the king on d2 and the queen on b2." },
      ja: { title: "黒ナイトの両取り", prompt: "BLACK: チェックしながら白のクイーンも攻撃してください。", hint: "Nc4+でd2のキングとb2のクイーンを同時に狙えます。" },
    },
  },
  {
    id: "absolute_pin_setup",
    title: "나이트 체크로 퀸 공격 열기",
    prompt: "WHITE: 나이트 체크와 동시에 룩의 퀸 공격선을 여세요.",
    hint: "Ne7+로 템포를 얻으면 d파일이 열려 d1 룩이 d8 퀸을 공격합니다.",
    fen: "3q2k1/8/8/3N4/8/8/8/3R2K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d5e7"]],
    tags: ["clearance", "discovered-attack", "double-attack", "knight", "check"],
    localized: {
      en: { title: "Uncover the Queen Attack", prompt: "WHITE: Check with the knight while opening the rook's line to the queen.", hint: "Ne7+ gains a tempo and clears the d-file, so the rook on d1 attacks the queen on d8." },
      ja: { title: "ナイトチェックでクイーン攻撃を開く", prompt: "WHITE: ナイトでチェックしながら、ルークからクイーンへの攻撃線を開いてください。", hint: "Ne7+でテンポを得てdファイルを開き、d1のルークがd8のクイーンを攻撃します。" },
    },
  },
  {
    id: "black_absolute_pin",
    title: "룩으로 만드는 파일 핀",
    prompt: "BLACK: 룩을 g파일로 옮겨 나이트를 킹 앞에 고정하세요.",
    hint: "Rg8 뒤 g3 나이트가 움직이면 g1 킹이 룩 공격에 노출되므로 절대 핀이 됩니다.",
    fen: "r6k/8/8/8/8/6N1/8/6K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["a8g8"]],
    tags: ["pin", "rook", "file"],
    localized: {
      en: { title: "Rook File Pin", prompt: "BLACK: Shift the rook onto the g-file and pin the knight to its king.", hint: "After Rg8, moving the g3 knight would expose the king on g1 to the rook, so the pin is absolute." },
      ja: { title: "ルークによるファイルのピン", prompt: "BLACK: ルークをgファイルへ移し、ナイトをキングにピンしてください。", hint: "Rg8のあとg3のナイトが動くとg1のキングがルークにさらされるため、絶対ピンになります。" },
    },
  },
  {
    id: "clear_the_rook_file",
    title: "폰으로 비숍 대각선 열기",
    prompt: "WHITE: 폰을 전진시켜 숨어 있던 비숍 체크를 여세요.",
    hint: "e5+로 e4를 비우면 b1 비숍의 대각선이 h7 킹까지 곧게 열립니다.",
    fen: "8/7k/8/8/4P3/8/8/KB6 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e4e5"]],
    tags: ["clearance", "discovered-check", "bishop", "pawn"],
    localized: {
      en: { title: "Open the Bishop Diagonal", prompt: "WHITE: Advance the pawn to uncover the hidden bishop check.", hint: "e5+ vacates e4 and opens the b1-h7 diagonal all the way to the king." },
      ja: { title: "ポーンでビショップの対角線を開く", prompt: "WHITE: ポーンを進めて、隠れていたビショップのチェックを開いてください。", hint: "e5+でe4を空けると、b1からh7のキングまで対角線が開きます。" },
    },
  },
  {
    id: "rook_underpromotion_check",
    title: "포획하며 룩으로 언더프로모션",
    prompt: "WHITE: 마지막 칸의 룩을 잡고 새 룩으로 승급해 체크하세요.",
    hint: "gxh8=R+은 h8 룩을 제거하고 새 룩으로 e8 킹을 가로질러 체크합니다.",
    fen: "4k2r/6P1/8/8/8/8/8/K7 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["g7h8r"]],
    tags: ["promotion", "underpromotion", "capture", "check"],
    localized: {
      en: { title: "Capture and Underpromote to a Rook", prompt: "WHITE: Capture the rook on the last rank and promote to a new rook with check.", hint: "gxh8=R+ removes the h8 rook and checks the king on e8 across the rank." },
      ja: { title: "取りながらルークへアンダープロモーション", prompt: "WHITE: 最終段のルークを取り、新しいルークに昇格してチェックしてください。", hint: "gxh8=R+でh8のルークを取り、昇格したルークがe8のキングを横からチェックします。" },
    },
  },
  {
    id: "black_knight_underpromotion",
    title: "흑의 나이트 승급",
    prompt: "BLACK: 폰을 나이트로 승급하세요.",
    hint: "e1에 도착한 폰을 나이트로 바꾸세요.",
    fen: "7k/8/8/8/8/8/4p3/K7 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["e2e1n"]],
    tags: ["promotion", "underpromotion", "knight"],
    localized: {
      en: { title: "Black Knight Promotion", prompt: "BLACK: Promote the pawn to a knight.", hint: "Choose a knight when the pawn reaches e1." },
      ja: { title: "黒のナイト昇格", prompt: "BLACK: ポーンをナイトに昇格してください。", hint: "e1に着いたポーンをナイトに変えます。" },
    },
  },
  {
    id: "remove_the_queen",
    title: "중앙의 퀸 제거",
    prompt: "WHITE: 비숍의 대각선으로 상대 퀸을 제거하세요.",
    hint: "c4의 비숍은 d5를 바로 공격합니다.",
    fen: "6k1/5ppp/8/3q4/2B5/8/8/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4d5"]],
    tags: ["removal", "capture", "bishop"],
    localized: {
      en: { title: "Remove the Queen", prompt: "WHITE: Use the bishop's diagonal to remove the enemy queen.", hint: "The bishop on c4 attacks d5 directly." },
      ja: { title: "中央のクイーンを除去", prompt: "WHITE: ビショップの対角線で相手のクイーンを取ってください。", hint: "c4のビショップはd5を直接攻撃しています。" },
    },
  },
  {
    id: "rook_ladder_finish",
    title: "룩의 마지막 계단",
    prompt: "WHITE: 룩을 마지막 줄에 올려 체크메이트하세요.",
    hint: "a파일을 끝까지 올라가면 흑 킹의 탈출 칸이 사라집니다.",
    fen: "7k/6pp/8/8/8/8/8/R6K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a1a8"]],
    tags: ["mate-in-1", "rook"],
    localized: {
      en: { title: "Rook Ladder Finish", prompt: "WHITE: Send the rook to the back rank for checkmate.", hint: "Ra8 leaves the black king no escape square." },
      ja: { title: "ルークの最終段", prompt: "WHITE: ルークを最終段へ運んでチェックメイトしてください。", hint: "Ra8で黒キングの逃げ道がなくなります。" },
    },
  },
  {
    id: "black_rook_invasion",
    title: "흑 룩의 침투",
    prompt: "BLACK: 열린 a파일을 따라 내려가 백 킹을 체크하세요.",
    hint: "a8의 룩을 a1까지 내려보내세요.",
    fen: "r5k1/5ppp/8/8/8/8/8/6K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["a8a1"]],
    tags: ["invasion", "check", "rook"],
    localized: {
      en: { title: "Black Rook Invasion", prompt: "BLACK: Invade down the open a-file with check.", hint: "Send the rook from a8 to a1." },
      ja: { title: "黒ルークの侵入", prompt: "BLACK: 開いたaファイルを侵入してチェックしてください。", hint: "a8のルークをa1まで動かします。" },
    },
  },
  {
    id: "queen_removes_invader",
    title: "침투한 룩 제거",
    prompt: "WHITE: 퀸으로 중앙에 침투한 룩을 잡으세요.",
    hint: "c3의 퀸이 d4로 한 칸 대각선 이동할 수 있습니다.",
    fen: "6k1/5ppp/8/8/3r4/2Q5/8/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c3d4"]],
    tags: ["removal", "capture", "queen"],
    localized: {
      en: { title: "Remove the Invading Rook", prompt: "WHITE: Capture the rook that invaded the center.", hint: "The queen on c3 can move one diagonal step to d4." },
      ja: { title: "侵入したルークを除去", prompt: "WHITE: 中央へ侵入したルークをクイーンで取ってください。", hint: "c3のクイーンはd4へ斜めに1マス動けます。" },
    },
  },
  {
    id: "fried_liver_sequence",
    title: "프라이드 리버 포크",
    prompt: "WHITE: f7에 희생해 킹을 끌어낸 뒤 퀸으로 체크하세요.",
    hint: "나이트가 f7을 잡으면 킹이 나온 뒤 Qf3+가 이어집니다.",
    fen: "r1bqkb1r/ppp2ppp/2n5/3np1N1/2B5/8/PPPP1PPP/RNBQK2R w KQkq - 0 6",
    playerColor: "w",
    solutionSteps: [["g5f7"], ["e8f7"], ["d1f3"]],
    tags: ["sacrifice", "fork", "check", "two-step"],
    localized: {
      en: { title: "Fried Liver Fork", prompt: "WHITE: Sacrifice on f7, draw out the king, then check with the queen.", hint: "Nxf7 is followed by Kxf7 and Qf3+." },
      ja: { title: "フライドリバー・フォーク", prompt: "WHITE: f7に犠牲を入れてキングを引き出し、クイーンでチェックしてください。", hint: "Nxf7 Kxf7のあとQf3+です。" },
    },
  },
  {
    id: "legals_mate_sequence",
    title: "레갈의 메이트",
    prompt: "WHITE: 퀸을 내준 대신 두 기물로 킹을 몰아 체크메이트하세요.",
    hint: "Bxf7+로 킹을 e7에 유인한 뒤 Nd5#입니다.",
    fen: "r2qkbnr/ppp2ppp/2np4/4N3/2B1P3/2N5/PPPP1PPP/R1BbK2R w KQkq - 0 6",
    playerColor: "w",
    solutionSteps: [["c4f7"], ["e8e7"], ["c3d5"]],
    tags: ["sacrifice", "mate-in-2", "knight", "two-step"],
    localized: {
      en: { title: "Legal's Mate", prompt: "WHITE: Ignore the lost queen and mate with two minor pieces.", hint: "Bxf7+ draws the king to e7, then Nd5 is mate." },
      ja: { title: "レガルのメイト", prompt: "WHITE: クイーンを失っても、小駒2つでチェックメイトしてください。", hint: "Bxf7+でキングをe7へ誘い、Nd5#です。" },
    },
  },
  {
    id: "damiano_punishment",
    title: "다미아노 약점 공략",
    prompt: "WHITE: 열린 킹 쪽을 연속 체크로 공략하세요.",
    hint: "Qh5+에 g6으로 막으면 Qxe5+로 중앙 폰을 잡습니다.",
    fen: "rnbqkbnr/pppp2pp/8/4p3/4P3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 4",
    playerColor: "w",
    solutionSteps: [["d1h5"], ["g7g6"], ["h5e5"]],
    tags: ["check", "removal", "queen", "two-step"],
    localized: {
      en: { title: "Punish Damiano's Weakness", prompt: "WHITE: Exploit the exposed king with consecutive checks.", hint: "After Qh5+ and ...g6, take on e5 with check." },
      ja: { title: "ダミアーノの弱点を攻める", prompt: "WHITE: 露出したキングを連続チェックで攻めてください。", hint: "Qh5+ g6のあとQxe5+です。" },
    },
  },
  {
    id: "greek_gift_attack",
    title: "그릭 기프트",
    prompt: "WHITE: 비숍을 희생해 킹을 끌어낸 뒤 나이트로 추격하세요.",
    hint: "Bxh7+ Kxh7 뒤 Ng5+로 공격을 이어갑니다.",
    fen: "rnbq1rk1/ppp1bppp/4pn2/3p4/3P4/3BPN2/PPP2PPP/RNBQ1RK1 w - - 4 6",
    playerColor: "w",
    solutionSteps: [["d3h7"], ["g8h7"], ["f3g5"]],
    tags: ["sacrifice", "check", "attack", "two-step"],
    localized: {
      en: { title: "Greek Gift Attack", prompt: "WHITE: Sacrifice the bishop, draw out the king, and chase it with the knight.", hint: "Bxh7+ Kxh7 is followed by Ng5+." },
      ja: { title: "ギリシャの贈り物", prompt: "WHITE: ビショップを犠牲にしてキングを引き出し、ナイトで追撃してください。", hint: "Bxh7+ Kxh7のあとNg5+です。" },
    },
  },
  {
    id: "knight_fork_then_rook",
    title: "체크 포크 뒤 룩 획득",
    prompt: "WHITE: 체크 포크로 킹을 움직인 뒤 구석의 룩을 잡으세요.",
    hint: "Nc7+로 킹과 a8 룩을 동시에 공격합니다.",
    fen: "r3k3/8/8/1N6/8/8/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["b5c7"], ["e8d8"], ["c7a8"]],
    tags: ["fork", "knight", "capture", "two-step"],
    localized: {
      en: { title: "Check Fork Wins the Rook", prompt: "WHITE: Fork with check, then collect the corner rook.", hint: "Nc7+ attacks both the king and the rook on a8." },
      ja: { title: "チェックフォークでルーク獲得", prompt: "WHITE: チェックのフォークをかけ、隅のルークを取ってください。", hint: "Nc7+でキングとa8のルークを同時に攻撃します。" },
    },
  },
  {
    id: "rook_king_queen_skewer",
    title: "룩의 킹-퀸 스큐어",
    prompt: "WHITE: 룩으로 킹을 몰아낸 뒤 뒤에 있던 퀸을 잡으세요.",
    hint: "Re1+로 킹을 움직이면 e8의 퀸이 남습니다.",
    fen: "4q3/4k3/8/8/8/8/8/R5K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a1e1"], ["e7d6"], ["e1e8"]],
    tags: ["skewer", "rook", "capture", "two-step"],
    localized: {
      en: { title: "Rook King-Queen Skewer", prompt: "WHITE: Drive the king away, then take the queen behind it.", hint: "Re1+ moves the king and leaves the queen on e8 exposed." },
      ja: { title: "ルークのキング・クイーン串刺し", prompt: "WHITE: キングを追い払い、その後ろのクイーンを取ってください。", hint: "Re1+でキングを動かすとe8のクイーンが残ります。" },
    },
  },
  {
    id: "bishop_lure_queen_win",
    title: "비숍 희생으로 퀸 획득",
    prompt: "WHITE: 비숍 체크로 킹을 유인한 뒤 상대 퀸을 잡으세요.",
    hint: "Bxf7+ Kxf7 뒤 열린 d파일의 퀸을 노리세요.",
    fen: "3qk3/5p2/8/8/2B5/8/8/3Q2K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4f7"], ["e8f7"], ["d1d8"]],
    tags: ["sacrifice", "deflection", "capture", "two-step"],
    localized: {
      en: { title: "Bishop Lure Wins the Queen", prompt: "WHITE: Lure the king with a bishop check, then take the queen.", hint: "After Bxf7+ Kxf7, the queen on d8 is exposed." },
      ja: { title: "ビショップの誘いでクイーン獲得", prompt: "WHITE: ビショップのチェックでキングを誘い、クイーンを取ってください。", hint: "Bxf7+ Kxf7のあとd8のクイーンが無防備です。" },
    },
  },
  {
    id: "smothered_queen_sacrifice",
    title: "퀸 희생 스머더드 메이트",
    prompt: "WHITE: 퀸을 희생해 룩을 유인한 뒤 나이트로 메이트하세요.",
    hint: "Qg8+ Rxg8 뒤 Nf7#로 킹을 완전히 가둡니다.",
    fen: "5r1k/6pp/4Q2N/8/8/8/8/K7 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e6g8"], ["f8g8"], ["h6f7"]],
    tags: ["sacrifice", "deflection", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Smothered Mate Queen Sacrifice", prompt: "WHITE: Sacrifice the queen to deflect the rook, then mate with the knight.", hint: "Qg8+ Rxg8 allows Nf7#." },
      ja: { title: "クイーン犠牲の窒息メイト", prompt: "WHITE: クイーンを犠牲にしてルークをそらし、ナイトでメイトしてください。", hint: "Qg8+ Rxg8のあとNf7#です。" },
    },
  },
  {
    id: "back_rank_deflection",
    title: "백랭크 디플렉션",
    prompt: "WHITE: 퀸을 희생해 수비 룩을 끌어낸 뒤 메이트하세요.",
    hint: "Qxe8+로 첫 룩을 제거하면 a8 룩의 Rxe8이 강제되고, 이어 Rxe8#입니다.",
    fen: "r3r1k1/5ppp/8/8/8/8/4Q3/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e2e8"], ["a8e8"], ["e1e8"]],
    tags: ["sacrifice", "deflection", "back-rank", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Back-Rank Deflection", prompt: "WHITE: Sacrifice the queen to deflect the rook, then deliver mate.", hint: "Qxe8+ removes the first rook and forces the a8 rook to recapture; then Rxe8 is mate." },
      ja: { title: "バックランクのそらし", prompt: "WHITE: クイーンを犠牲にして守備のルークをそらし、メイトしてください。", hint: "Qxe8+で最初のルークを取り、a8のルークにRxe8を強制してからRxe8#です。" },
    },
  },
  {
    id: "promotion_deflection",
    title: "승급 디플렉션",
    prompt: "WHITE: 체크 승급으로 룩을 유인한 뒤 다시 잡으세요.",
    hint: "e8=Q+로 a8 룩을 e8에 끌어오면 아래 룩이 잡을 수 있습니다.",
    fen: "r6k/4P3/8/8/8/8/8/4R2K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e7e8q"], ["a8e8"], ["e1e8"]],
    tags: ["promotion", "sacrifice", "deflection", "two-step"],
    localized: {
      en: { title: "Promotion Deflection", prompt: "WHITE: Promote with check to deflect the rook, then recapture it.", hint: "e8=Q+ pulls the a8 rook onto e8 for your other rook." },
      ja: { title: "昇格によるそらし", prompt: "WHITE: チェック付き昇格でルークをそらし、取り返してください。", hint: "e8=Q+でa8のルークをe8へ誘います。" },
    },
  },
  {
    id: "black_smothered_finish",
    title: "흑의 스머더드 메이트",
    prompt: "BLACK: 퀸을 희생해 룩을 유인하고 나이트로 메이트하세요.",
    hint: "Qg1+ Rxg1 뒤 Nf2#가 완성됩니다.",
    fen: "7k/8/8/8/8/4q2n/6PP/5R1K b - - 0 1",
    playerColor: "b",
    solutionSteps: [["e3g1"], ["f1g1"], ["h3f2"]],
    tags: ["sacrifice", "deflection", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Black Smothered Finish", prompt: "BLACK: Sacrifice the queen to deflect the rook, then mate with the knight.", hint: "Qg1+ Rxg1 is followed by Nf2#." },
      ja: { title: "黒の窒息メイト", prompt: "BLACK: クイーンを犠牲にしてルークをそらし、ナイトでメイトしてください。", hint: "Qg1+ Rxg1のあとNf2#です。" },
    },
  },
  {
    id: "black_rook_skewer",
    title: "룩 희생으로 퀸 끌어내기",
    prompt: "BLACK: 룩을 희생해 백 퀸의 강제 포획을 유도한 뒤 비숍으로 퀸을 잡으세요.",
    hint: "Re1+에는 Qxe1만 가능하고, d3이 비워진 대각선으로 Bxe1이 이어집니다.",
    fen: "4r1k1/8/8/8/1b6/8/5PPP/3Q2K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["e8e1"], ["d1e1"], ["b4e1"]],
    tags: ["sacrifice", "deflection", "bishop", "capture", "two-step"],
    localized: {
      en: { title: "Rook Sacrifice Deflects the Queen", prompt: "BLACK: Sacrifice the rook to force the white queen onto a square where the bishop can capture it.", hint: "Re1+ permits only Qxe1, after which the cleared diagonal gives Bxe1." },
      ja: { title: "ルーク犠牲でクイーンを誘う", prompt: "BLACK: ルークを犠牲にして白のクイーンに強制的に取らせ、ビショップでそのクイーンを取ってください。", hint: "Re1+にはQxe1しかなく、d3が空いた対角線からBxe1と続きます。" },
    },
  },
  {
    id: "rook_block_deflection",
    title: "수비 룩 끌어내기",
    prompt: "WHITE: 체크로 룩의 방어를 강제한 뒤 그 룩을 잡으세요.",
    hint: "Qe8+에 Rf8로 막으면 Qxf8+로 제거할 수 있습니다.",
    fen: "6k1/5rpp/8/8/8/8/4Q3/3R2K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e2e8"], ["f7f8"], ["e8f8"]],
    tags: ["deflection", "removal", "queen", "two-step"],
    localized: {
      en: { title: "Deflect the Defending Rook", prompt: "WHITE: Force the rook to block, then remove it.", hint: "Qe8+ forces Rf8, allowing Qxf8+." },
      ja: { title: "守備ルークをおびき出す", prompt: "WHITE: ルークにブロックを強制し、そのルークを取ってください。", hint: "Qe8+にRf8ならQxf8+です。" },
    },
  },
  {
    id: "clearance_back_rank_sac",
    title: "클리어런스 백랭크 희생",
    prompt: "WHITE: 첫 룩을 희생해 두 번째 룩의 백랭크 메이트 길을 여세요.",
    hint: "Rxd8+ Bxd8 뒤 Re8#입니다. 클리어런스는 기물을 비워 다른 기물의 공격로를 여는 전술입니다.",
    fen: "3q2k1/2b2ppp/8/8/8/8/8/3RR1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1d8"], ["c7d8"], ["e1e8"]],
    tags: ["clearance", "sacrifice", "back-rank", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Clearance Back-Rank Sacrifice", prompt: "WHITE: Sacrifice the first rook to clear a back-rank mating lane for the second.", hint: "Rxd8+ Bxd8 allows Re8#. Clearance means vacating a line so another piece can use it." },
      ja: { title: "クリアランスのバックランク犠牲", prompt: "WHITE: 1台目のルークを犠牲にし、2台目のルークのメイトラインを開いてください。", hint: "Rxd8+ Bxd8のあとRe8#です。クリアランスとは、別の駒の攻撃路を開けるためにマスやラインを空ける戦術です。" },
    },
  },
  {
    id: "discovered_queen_hunt",
    title: "디스커버드 어택으로 퀸 사냥",
    prompt: "WHITE: 비숍 체크로 룩을 유인하면서 뒤 룩의 퀸 공격을 여세요.",
    hint: "Bh7+ Rxh7 뒤 Rxe8입니다. 디스커버드 어택은 앞 기물이 움직이며 뒤 기물의 공격선을 드러내는 전술입니다.",
    fen: "4qbkr/5pp1/8/8/4B3/8/2Q5/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e4h7"], ["h8h7"], ["e1e8"]],
    tags: ["discovered-attack", "deflection", "sacrifice", "capture", "two-step"],
    localized: {
      en: { title: "Discovered Attack Queen Hunt", prompt: "WHITE: Use a bishop check to lure the rook while uncovering an attack on the queen.", hint: "Bh7+ Rxh7 is followed by Rxe8. A discovered attack reveals a rear piece's line by moving the piece in front." },
      ja: { title: "ディスカバードアタックでクイーン獲得", prompt: "WHITE: ビショップのチェックでルークを誘い、後方のルークによるクイーン攻撃を開いてください。", hint: "Bh7+ Rxh7のあとRxe8です。ディスカバードアタックとは、前の駒を動かして後ろの駒の攻撃線を開く戦術です。" },
    },
  },
  {
    id: "underpromotion_royal_fork",
    title: "언더프로모션 왕실 포크",
    prompt: "WHITE: 퀸이 아닌 기물로 승급해 킹과 퀸을 동시에 공격하세요.",
    hint: "c8=N+ Ka6 뒤 Nxe7입니다. 언더프로모션은 퀸보다 약한 기물을 의도적으로 선택하는 승급입니다.",
    fen: "rb6/kpP1q3/8/8/8/8/8/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c7c8n"], ["a7a6"], ["c8e7"]],
    tags: ["underpromotion", "promotion", "fork", "capture", "two-step"],
    localized: {
      en: { title: "Underpromotion Royal Fork", prompt: "WHITE: Promote to something other than a queen and attack the king and queen at once.", hint: "c8=N+ Ka6 is followed by Nxe7. Underpromotion deliberately chooses a piece weaker than a queen." },
      ja: { title: "アンダープロモーションのロイヤルフォーク", prompt: "WHITE: クイーン以外に昇格し、キングとクイーンを同時に攻撃してください。", hint: "c8=N+ Ka6のあとNxe7です。アンダープロモーションとは、意図的にクイーンより弱い駒を選ぶ昇格です。" },
    },
  },
  {
    id: "anastasia_mating_net",
    title: "아나스타샤 메이트",
    prompt: "WHITE: 나이트로 킹의 옆칸을 봉쇄하고 퀸 희생 뒤 룩 스윙으로 끝내세요.",
    hint: "Ne7+ Kh8, Qxh7+ Kxh7 뒤 Rh3#입니다. 아나스타샤 메이트는 나이트와 룩이 보드 가장자리의 킹을 가두는 패턴입니다.",
    fen: "5rk1/5ppp/6N1/7Q/8/R7/8/K7 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["g6e7"], ["g8h8"], ["h5h7"], ["h8h7"], ["a3h3"]],
    tags: ["anastasia-mate", "sacrifice", "rook-lift", "mate-in-3", "three-step"],
    localized: {
      en: { title: "Anastasia's Mating Net", prompt: "WHITE: Seal the king's side squares with the knight, sacrifice the queen, and finish with a rook swing.", hint: "Ne7+ Kh8, Qxh7+ Kxh7, then Rh3#. Anastasia's mate traps an edge king with a knight and rook." },
      ja: { title: "アナスタシアのメイト", prompt: "WHITE: ナイトでキングの横を封鎖し、クイーンを犠牲にしてルークスイングで仕留めてください。", hint: "Ne7+ Kh8、Qxh7+ Kxh7のあとRh3#です。アナスタシアのメイトは、ナイトとルークで端のキングを閉じ込める形です。" },
    },
  },
  {
    id: "boden_mate_clearance",
    title: "보덴 메이트의 대각선",
    prompt: "WHITE: 퀸을 희생해 b폰을 비운 뒤 두 비숍의 교차 공격으로 메이트하세요.",
    hint: "Qxc6+ bxc6 뒤 Ba6#입니다. 보덴 메이트는 열린 두 대각선이 킹의 탈출 칸을 교차해 막는 패턴입니다.",
    fen: "2kr4/1p1n4/2n5/8/Q1B2B2/8/8/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a4c6"], ["b7c6"], ["c4a6"]],
    tags: ["boden-mate", "clearance", "queen-sacrifice", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Boden's Mate Clearance", prompt: "WHITE: Sacrifice the queen to clear the b-pawn, then mate with crossing bishop diagonals.", hint: "Qxc6+ bxc6 allows Ba6#. Boden's mate uses two open diagonals to cover the king's escape squares." },
      ja: { title: "ボーデンメイトのクリアランス", prompt: "WHITE: クイーンを犠牲にしてbポーンを動かし、2本のビショップの対角線でメイトしてください。", hint: "Qxc6+ bxc6のあとBa6#です。ボーデンメイトは、開いた2本の対角線がキングの逃げ道を交差して封じる形です。" },
    },
  },
  {
    id: "double_check_clearance",
    title: "더블 체크 클리어런스",
    prompt: "WHITE: 비숍을 움직여 비숍과 룩의 더블 체크를 만들고 킹을 메이트망으로 모세요.",
    hint: "Bb5+는 두 기물이 동시에 체크하므로 킹만 움직일 수 있습니다. Kd8 뒤 Re8#입니다.",
    fen: "4kn2/5p2/8/8/5B2/8/4B3/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e2b5"], ["e8d8"], ["e1e8"]],
    tags: ["double-check", "clearance", "discovered-check", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Double-Check Clearance", prompt: "WHITE: Move the bishop to create a bishop-and-rook double check, then drive the king into mate.", hint: "Bb5+ checks with two pieces, so only a king move can answer it. After Kd8, play Re8#." },
      ja: { title: "ダブルチェックのクリアランス", prompt: "WHITE: ビショップを動かしてビショップとルークのダブルチェックを作り、キングをメイト網へ追い込んでください。", hint: "Bb5+は2つの駒が同時にチェックするため、キングを動かすしかありません。Kd8のあとRe8#です。" },
    },
  },
  {
    id: "windmill_queen_harvest",
    title: "윈드밀 더블 수확",
    prompt: "WHITE: 룩과 비숍의 왕복 체크로 룩을 잡고, 다시 돌아와 나이트까지 안전하게 거두세요.",
    hint: "Rxf7+ Kg8, Rg7+ Kh8 뒤 Rxb7+입니다. 바로 Rxb7이면 ...Rxb7이 가능하지만 윈드밀 체크를 끼우면 룩을 보존합니다.",
    fen: "1r5k/1n3rR1/8/8/1B6/2B5/8/5R1K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["g7f7"], ["h8g8"], ["f7g7"], ["g8h8"], ["g7b7"]],
    tags: ["windmill", "discovered-check", "capture", "three-step"],
    localized: {
      en: { title: "Windmill Double Harvest", prompt: "WHITE: Alternate rook and bishop checks to take the rook, return, and safely collect the knight too.", hint: "Rxf7+ Kg8, Rg7+ Kh8, then Rxb7+. Playing Rxb7 immediately allows ...Rxb7; the windmill checks preserve your rook." },
      ja: { title: "ウィンドミルの二重収穫", prompt: "WHITE: ルークとビショップの往復チェックでルークを取り、戻ってナイトも安全に取ってください。", hint: "Rxf7+ Kg8、Rg7+ Kh8のあとRxb7+です。すぐRxb7では...Rxb7が可能ですが、ウィンドミルのチェックを挟めばルークを残せます。" },
    },
  },
  {
    id: "interference_back_rank_net",
    title: "인터피어런스 백랭크 망",
    prompt: "WHITE: 비숍 희생으로 룩을 끌어내고, 강제 차단 수를 이용해 백랭크 메이트하세요.",
    hint: "Bxf7+ Rxf7, Re8+ Rf8 뒤 Rxf8#입니다. 인터피어런스는 수비 기물이 다른 수비선에 끼어들게 만드는 전술입니다.",
    fen: "5rkr/5ppp/8/2B5/2B5/8/8/4RR1K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4f7"], ["f8f7"], ["e1e8"], ["f7f8"], ["e8f8"]],
    tags: ["interference", "deflection", "back-rank", "mate-in-3", "three-step"],
    localized: {
      en: { title: "Interference Back-Rank Net", prompt: "WHITE: Lure the rook with a bishop sacrifice, then exploit its forced block for a back-rank mate.", hint: "Bxf7+ Rxf7, Re8+ Rf8, then Rxf8#. Interference makes one defender obstruct another defensive line." },
      ja: { title: "干渉のバックランク網", prompt: "WHITE: ビショップの犠牲でルークを誘い、強制ブロックを利用してバックランクメイトしてください。", hint: "Bxf7+ Rxf7、Re8+ Rf8のあとRxf8#です。干渉とは、守備駒に別の守備線を遮らせる戦術です。" },
    },
  },
  {
    id: "queen_deflection_mate",
    title: "퀸 디플렉션 메이트",
    prompt: "WHITE: 룩을 희생해 수비 퀸을 끌어낸 뒤 g7에서 메이트하세요.",
    hint: "Re8+ Qxe8 뒤 Qxg7#입니다. 디플렉션은 수비 기물을 핵심 방어 임무에서 떼어내는 전술입니다.",
    fen: "6k1/3q1ppp/8/8/8/2Q5/8/4R1RK w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e8"], ["d7e8"], ["c3g7"]],
    tags: ["deflection", "rook-sacrifice", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Queen Deflection Mate", prompt: "WHITE: Sacrifice the rook to drag away the defending queen, then mate on g7.", hint: "Re8+ Qxe8 allows Qxg7#. Deflection pulls a defender away from its essential duty." },
      ja: { title: "クイーンのそらしメイト", prompt: "WHITE: ルークを犠牲にして守備のクイーンを誘い出し、g7でメイトしてください。", hint: "Re8+ Qxe8のあとQxg7#です。そらしとは、守備駒を重要な防御任務から引き離す戦術です。" },
    },
  },
  {
    id: "promotion_back_rank_combo",
    title: "승급 백랭크 콤비네이션",
    prompt: "WHITE: 룩 교환으로 승급 칸을 비우고 체크메이트 승급을 완성하세요.",
    hint: "Rxd8+ Rxd8 뒤 cxd8=Q#입니다. 교환이 d8을 비우면서 폰의 마지막 대각선 포획을 준비합니다.",
    fen: "r2r2k1/2P2ppp/8/8/8/8/8/3R2K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1d8"], ["a8d8"], ["c7d8q"]],
    tags: ["promotion", "clearance", "back-rank", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Promotion Back-Rank Combination", prompt: "WHITE: Trade rooks to clear the promotion square, then promote with checkmate.", hint: "Rxd8+ Rxd8 permits cxd8=Q#. The exchange clears d8 for the pawn's final diagonal capture." },
      ja: { title: "昇格のバックランク・コンビネーション", prompt: "WHITE: ルーク交換で昇格マスを空け、チェックメイトの昇格を決めてください。", hint: "Rxd8+ Rxd8のあとcxd8=Q#です。交換によってd8が空き、ポーンの最後の斜め取りが可能になります。" },
    },
  },
  {
    id: "zwischenzug_before_recapture",
    title: "되잡기 전 츠비셴추크",
    prompt: "WHITE: 퀸을 바로 되잡기 전에 체크를 끼워 넣어 템포를 확보하세요.",
    hint: "Ne7+ Kh8 뒤 Qxa1입니다. 츠비셴추크는 예상된 대응보다 먼저 두는 강제 중간 수입니다.",
    fen: "5rk1/5ppp/2N5/8/8/8/8/q2Q3K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c6e7"], ["g8h8"], ["d1a1"]],
    tags: ["zwischenzug", "check", "recapture", "two-step"],
    localized: {
      en: { title: "Zwischenzug Before Recapture", prompt: "WHITE: Insert a check before recapturing the queen and gain a tempo.", hint: "Ne7+ Kh8 comes before Qxa1. A zwischenzug is a forcing intermediate move played before the expected reply." },
      ja: { title: "取り返す前のツヴィッシェンツーク", prompt: "WHITE: クイーンを取り返す前にチェックを挟み、テンポを得てください。", hint: "Ne7+ Kh8のあとQxa1です。ツヴィッシェンツークとは、予想される応手より先に指す強制的な中間手です。" },
    },
  },
  {
    id: "black_discovered_queen_hunt",
    title: "더블 체크로 퀸 사냥",
    prompt: "BLACK: 비숍을 움직여 룩의 디스커버드 체크와 비숍 체크를 동시에 만들고 퀸을 잡으세요.",
    hint: "Bc3+는 더블 체크라 Kd1만 가능하며, 이어 Bxa1로 퀸을 잡습니다.",
    fen: "4r1k1/8/8/4b3/8/8/5P2/Q3KR2 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["e5c3"], ["e1d1"], ["c3a1"]],
    tags: ["discovered-check", "double-check", "double-attack", "capture", "two-step"],
    localized: {
      en: { title: "Double Check Hunts the Queen", prompt: "BLACK: Move the bishop to create both a discovered rook check and a bishop check, then take the queen.", hint: "Bc3+ is a double check, so Kd1 is the only reply; then Bxa1 wins the queen." },
      ja: { title: "ダブルチェックでクイーン狩り", prompt: "BLACK: ビショップを動かし、ルークのディスカバードチェックとビショップのチェックを同時に作ってクイーンを取ってください。", hint: "Bc3+はダブルチェックなのでKd1しかなく、そのあとBxa1でクイーンを取ります。" },
    },
  },
  {
    id: "epaulette_interference_mate",
    title: "에폴레트 인터피어런스 메이트",
    prompt: "WHITE: 비숍의 강제 차단을 유도한 뒤 양옆 룩에 갇힌 킹을 메이트하세요.",
    hint: "Qe5+ Be6 뒤 Qxe6#입니다. 에폴레트 메이트는 킹 양옆의 자기 기물이 어깨장식처럼 탈출을 막는 형태입니다.",
    fen: "2brkr2/8/8/Q7/2B3B1/8/8/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a5e5"], ["c8e6"], ["e5e6"]],
    tags: ["epaulette-mate", "interference", "removal", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Epaulette Interference Mate", prompt: "WHITE: Force the bishop to interpose, then mate the king trapped between its own rooks.", hint: "Qe5+ Be6 allows Qxe6#. In an epaulette mate, the king's own pieces sit like shoulder ornaments and block both side escapes." },
      ja: { title: "エポレットの干渉メイト", prompt: "WHITE: ビショップにブロックを強制し、両側のルークに挟まれたキングをメイトしてください。", hint: "Qe5+ Be6のあとQxe6#です。エポレットメイトは、キングの両側の味方駒が肩飾りのように逃げ道を塞ぐ形です。" },
    },
  },
  {
    id: "black_clearance_back_rank",
    title: "흑의 클리어런스 백랭크",
    prompt: "BLACK: 퀸의 이동으로 비숍 대각선을 열고 룩의 마지막 줄 메이트를 준비하세요.",
    hint: "Qf1+ Rxf1 뒤 Rxf1#입니다. 퀸이 d3을 비워 비숍이 마지막 룩을 보호하게 합니다.",
    fen: "5rk1/8/8/8/2b5/3q4/6PP/4R1K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["d3f1"], ["e1f1"], ["f8f1"]],
    tags: ["clearance", "queen-sacrifice", "back-rank", "mate-in-2", "two-step"],
    localized: {
      en: { title: "Black's Clearance Back-Rank Mate", prompt: "BLACK: Move the queen to clear the bishop's diagonal and prepare a rook mate on the first rank.", hint: "Qf1+ Rxf1 permits Rxf1#. Vacating d3 lets the bishop protect the final rook." },
      ja: { title: "黒のクリアランス・バックランク", prompt: "BLACK: クイーンを動かしてビショップの対角線を開き、ルークの最終段メイトを準備してください。", hint: "Qf1+ Rxf1のあとRxf1#です。クイーンがd3を空けることで、ビショップが最後のルークを守ります。" },
    },
  },
  {
    id: "en_passant_file_clearance",
    title: "앙파상 파일 클리어런스",
    prompt: "WHITE: 앙파상으로 e파일의 룩 체크를 열고 다음 수에 퀸을 잡으세요.",
    hint: "exd6 e.p.+ Kd7 뒤 dxc7입니다. 앙파상 포획은 e폰과 d폰을 동시에 e파일에서 치워 디스커버드 체크를 만듭니다.",
    fen: "3rkr2/2q2p2/8/3pP3/8/8/8/4R1K1 w - d6 0 1",
    playerColor: "w",
    solutionSteps: [["e5d6"], ["e8d7"], ["d6c7"]],
    tags: ["en-passant", "clearance", "discovered-check", "capture", "two-step"],
    localized: {
      en: { title: "En Passant File Clearance", prompt: "WHITE: Use en passant to open the rook's e-file check, then capture the queen.", hint: "exd6 e.p.+ Kd7 is followed by dxc7. The en-passant capture removes both pawns from the e-file and reveals the rook check." },
      ja: { title: "アンパッサンのファイル・クリアランス", prompt: "WHITE: アンパッサンでルークのeファイルのチェックを開き、次にクイーンを取ってください。", hint: "exd6 e.p.+ Kd7のあとdxc7です。アンパッサンによって2つのポーンがeファイルから消え、ディスカバードチェックが開きます。" },
    },
  },
  {
    id: "decoy_into_royal_fork",
    title: "디코이 뒤 왕실 포크",
    prompt: "WHITE: 룩을 희생해 킹을 e7로 유인하고 나이트 체크로 퀸까지 잡으세요.",
    hint: "Rxe7+ Kxe7, Nd5+ Kd6 뒤 Nxb6입니다. 디코이는 상대 기물을 전술이 통하는 칸으로 유인하는 수법입니다.",
    fen: "3nkn2/3prp2/1q6/8/5N2/8/8/4R2K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e7"], ["e8e7"], ["f4d5"], ["e7d6"], ["d5b6"]],
    tags: ["decoy", "sacrifice", "fork", "capture", "three-step"],
    localized: {
      en: { title: "Decoy into a Royal Fork", prompt: "WHITE: Sacrifice the rook to draw the king to e7, then use a knight check to win the queen.", hint: "Rxe7+ Kxe7, Nd5+ Kd6, then Nxb6. A decoy lures an enemy piece onto a square where a tactic works." },
      ja: { title: "デコイからロイヤルフォーク", prompt: "WHITE: ルークを犠牲にしてキングをe7へ誘い、ナイトのチェックでクイーンも取ってください。", hint: "Rxe7+ Kxe7、Nd5+ Kd6のあとNxb6です。デコイとは、相手の駒を戦術が成立するマスへ誘い込む手筋です。" },
    },
  },
];

export function getPuzzle(indexOrId) {
  if (typeof indexOrId === "string") {
    return PUZZLES.find((p) => p.id === indexOrId) || PUZZLES[0];
  }
  const raw = indexOrId ?? 0;
  const index = Math.max(0, Math.min(PUZZLES.length - 1, raw));
  return PUZZLES[index];
}
