import {
  getClearedPuzzleIds,
  isPuzzleCleared,
  markPuzzleCleared,
  PUZZLE_PROGRESS_KEY,
} from "./playerState.js";

export {
  getClearedPuzzleIds,
  isPuzzleCleared,
  markPuzzleCleared,
  PUZZLE_PROGRESS_KEY,
};

export const PUZZLES = [
  {
    id: "mate_scholar",
    title: "첫 번째 체크메이트",
    prompt: "WHITE: 약한 f7 칸을 노려 한 수로 끝내세요.",
    hint: "퀸이 f7로 들어가면 왕이 도망갈 곳이 없습니다.",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    playerColor: "w",
    solutionSteps: [["h5f7"]],
    tags: ["mate-in-1", "beginner"],
  },
  {
    id: "fools_mate",
    title: "가장 빠른 메이트",
    prompt: "BLACK: 열린 대각선을 이용해 즉시 체크메이트하세요.",
    hint: "흑 퀸이 h4로 가면 백 왕은 막을 수 없습니다.",
    fen: "rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2",
    playerColor: "b",
    solutionSteps: [["d8h4"]],
    tags: ["mate-in-1", "beginner"],
  },
  {
    id: "back_rank_mate",
    title: "백랭크 메이트",
    prompt: "WHITE: 룩으로 마지막 줄의 왕을 가둬보세요.",
    hint: "상대 폰들이 왕의 탈출 칸을 막고 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/6PP/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e8"]],
    tags: ["mate-in-1", "rook"],
  },
  {
    id: "rook_takes_queen",
    title: "공짜 퀸",
    prompt: "WHITE: 일직선으로 열린 길을 보고 가장 큰 기물을 잡으세요.",
    hint: "e파일 위에 룩이 지나갈 길이 비어 있습니다.",
    fen: "6k1/4qppp/8/8/8/8/6PP/3QR1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e7"]],
    tags: ["capture", "rook"],
  },
  {
    id: "answer_check",
    title: "체크를 해결하며 이득 보기",
    prompt: "WHITE: 체크를 막으면서 상대 퀸을 잡으세요.",
    hint: "퀸이나 룩으로 e2 칸을 잡을 수 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/4q1PP/3QR1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1e2", "e1e2"]],
    tags: ["check", "capture"],
  },
  {
    id: "knight_fork",
    title: "나이트 포크",
    prompt: "WHITE: 나이트로 체크를 걸며 퀸을 잡으세요.",
    hint: "나이트는 직선이 아니라 뛰어넘어 공격합니다.",
    fen: "r5k1/4qppp/8/3N4/8/8/6PP/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d5e7"]],
    tags: ["fork", "knight"],
  },
  {
    id: "castle_safe",
    title: "킹을 안전하게",
    prompt: "WHITE: 캐슬링으로 킹을 피신시키세요.",
    hint: "킹을 두 칸 오른쪽으로 움직이면 짧은 캐슬링입니다.",
    fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
    playerColor: "w",
    solutionSteps: [["e1g1"]],
    tags: ["rule", "castle"],
  },
  {
    id: "promotion_queen",
    title: "승급",
    prompt: "WHITE: 폰을 끝까지 전진시켜 퀸으로 승급하세요.",
    hint: "a폰을 a8까지 올리고 퀸을 선택합니다.",
    fen: "7k/P7/8/8/8/8/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a7a8q"]],
    tags: ["rule", "promotion"],
  },
  {
    id: "rook_file_mate",
    title: "열린 파일 메이트",
    prompt: "WHITE: 룩을 마지막 줄까지 올려 왕을 가두세요.",
    hint: "a파일이 완전히 열려 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/6PP/R5K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["a1a8"]],
    tags: ["mate-in-1", "rook"],
  },
  {
    id: "black_back_rank",
    title: "흑의 백랭크",
    prompt: "BLACK: 룩으로 백 왕을 마지막 줄에 묶어두세요.",
    hint: "e파일을 따라 내려가면 왕이 도망갈 곳이 없습니다.",
    fen: "4r1k1/6pp/8/8/8/8/5PPP/6K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["e8e1"]],
    tags: ["mate-in-1", "rook"],
  },
  {
    id: "bishop_takes_queen",
    title: "비숍의 대각선",
    prompt: "WHITE: 대각선 위의 가장 큰 기물을 잡으세요.",
    hint: "비숍은 c4에서 d5를 공격합니다.",
    fen: "6k1/5ppp/8/3q4/2B5/8/6PP/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4d5"]],
    tags: ["capture", "bishop"],
  },
  {
    id: "black_promotion",
    title: "흑의 승급",
    prompt: "BLACK: 폰을 끝까지 내려 퀸으로 승급하세요.",
    hint: "a폰을 a1까지 내리고 퀸을 선택합니다.",
    fen: "7k/8/8/8/8/8/p7/7K b - - 0 1",
    playerColor: "b",
    solutionSteps: [["a2a1q"]],
    tags: ["rule", "promotion"],
  },
  {
    id: "queen_takes_rook",
    title: "퀸으로 룩 잡기",
    prompt: "WHITE: 체크를 해결하면서 룩을 잡으세요.",
    hint: "퀸이 e2 칸으로 이동할 수 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/4r1PP/3Q2K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1e2"]],
    tags: ["check", "capture"],
  },
  {
    id: "knight_takes_rook",
    title: "나이트의 반격",
    prompt: "WHITE: 나이트로 공격받는 기물을 잡으세요.",
    hint: "나이트는 d4에서 e2로 점프할 수 있습니다.",
    fen: "6k1/5ppp/8/8/3N4/8/4r1PP/6K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d4e2"]],
    tags: ["knight", "capture"],
  },
  {
    id: "rook_defense",
    title: "룩으로 체크 해제",
    prompt: "WHITE: 체크를 막으며 상대 룩을 제거하세요.",
    hint: "같은 파일 위의 룩으로 e2 칸을 잡으세요.",
    fen: "6k1/5ppp/8/8/8/8/4r1PP/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e1e2"]],
    tags: ["check", "rook"],
  },
  {
    id: "black_queen_capture",
    title: "흑 퀸의 반격",
    prompt: "BLACK: 체크를 해결하면서 백 퀸을 잡으세요.",
    hint: "흑 퀸이 e2 칸으로 이동할 수 있습니다.",
    fen: "6k1/5ppp/8/8/8/8/4Q1PP/3q2K1 b - - 0 1",
    playerColor: "b",
    solutionSteps: [["d1e2"]],
    tags: ["check", "capture"],
  },
  {
    id: "en_passant",
    title: "앙파상",
    prompt: "WHITE: 방금 두 칸 전진한 흑 폰을 특별한 방법으로 잡으세요.",
    hint: "e5의 폰을 d6으로 대각선 이동해 흑 폰을 잡습니다.",
    fen: "7k/8/8/3pP3/8/8/8/7K w - d6 0 1",
    playerColor: "w",
    solutionSteps: [["e5d6"]],
    tags: ["rule", "en-passant"],
  },
  {
    id: "smothered_mate",
    title: "스머더드 메이트",
    prompt: "WHITE: 자기 기물에 둘러싸인 왕을 나이트로 체크메이트하세요.",
    hint: "e5의 나이트가 f7로 가면 흑 왕의 모든 탈출 칸이 막힙니다.",
    fen: "6rk/6pp/8/4N3/8/8/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e5f7"]],
    tags: ["mate-in-1", "knight"],
  },
  {
    id: "pin_knight",
    title: "움직일 수 없는 나이트",
    prompt: "WHITE: 비숍으로 나이트를 킹 앞에 고정하세요.",
    hint: "비숍을 b5에 놓으면 나이트 뒤에 흑 킹이 있습니다.",
    fen: "4k3/8/2n5/8/2B5/8/8/4K3 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c4b5"]],
    tags: ["pin", "bishop"],
  },
  {
    id: "bishop_skewer",
    title: "비숍 스큐어",
    prompt: "WHITE: 킹을 먼저 공격해 뒤에 있는 룩을 노리세요.",
    hint: "비숍을 b4로 옮기면 킹과 룩이 한 대각선에 놓입니다.",
    fen: "8/4r3/3k4/8/8/2B5/8/7K w - - 0 1",
    playerColor: "w",
    solutionSteps: [["c3b4"]],
    tags: ["skewer", "bishop"],
  },
  {
    id: "queen_double_attack",
    title: "퀸의 더블 어택",
    prompt: "WHITE: 체크를 걸면서 동시에 룩도 공격하세요.",
    hint: "퀸을 h5에 놓으면 킹과 h8의 룩을 함께 노립니다.",
    fen: "4k2r/8/8/8/8/8/8/3QK3 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["d1h5"]],
    tags: ["double-attack", "queen"],
  },
  {
    id: "discovered_check",
    title: "디스커버드 체크",
    prompt: "WHITE: 비숍을 움직여 뒤에 있던 룩의 공격길을 여세요.",
    hint: "e4의 비숍을 b7로 옮기면 e파일의 룩이 킹을 공격합니다.",
    fen: "4k3/8/8/8/4B3/8/8/4R1K1 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e4b7"]],
    tags: ["discovered-check", "rook"],
  },
  {
    id: "knight_underpromotion",
    title: "나이트 언더프로모션",
    prompt: "WHITE: 폰을 나이트로 승급해 즉시 체크하세요.",
    hint: "e8에서 퀸이 아닌 나이트를 선택해야 킹을 공격합니다.",
    fen: "8/4P1k1/8/8/8/8/8/K7 w - - 0 1",
    playerColor: "w",
    solutionSteps: [["e7e8n"]],
    tags: ["underpromotion", "knight"],
  },
  {
    id: "black_castle_long",
    title: "흑의 긴 캐슬링",
    prompt: "BLACK: 퀸 쪽으로 캐슬링해 킹을 안전하게 옮기세요.",
    hint: "e8의 킹을 c8로 두 칸 옮기면 긴 캐슬링입니다.",
    fen: "r3k2r/8/8/8/8/8/8/R3K2R b KQkq - 0 1",
    playerColor: "b",
    solutionSteps: [["e8c8"]],
    tags: ["rule", "castle"],
  },
];

export function getPuzzle(indexOrId) {
  if (typeof indexOrId === "string") {
    return PUZZLES.find((p) => p.id === indexOrId) || PUZZLES[0];
  }
  const raw = indexOrId ?? 0;
  const index = Math.max(0, Math.min(PUZZLES.length - 1, raw));
  return PUZZLES[index];
}
