export const ADVANCED_PUZZLES_B = [
  {
    id: "expert_083_queenside_decoy",
    title: "양쪽 날개의 봉쇄",
    prompt: "BLACK: 킹사이드 폰을 교환한 뒤 마지막 폰 템포로 퀸사이드를 잠그세요.",
    hint: "gxh6 gxh6 a4입니다. 킹사이드 교환 뒤 ...a4가 백의 a3과 b2 폰을 모두 묶어 백을 불리한 차례로 몰아넣습니다.",
    fen: "8/6pp/7P/p5P1/2k1K3/Pp6/1P6/8 b - - 0 41",
    playerColor: "b",
    solutionSteps: [["g7h6"], ["g5h6"], ["a5a4"]],
    tags: ["advanced", "defensiveMove", "endgame", "pawnEndgame", "zugzwang"],
    source: { provider: "lichess", puzzleId: "12kUF", rating: 2156 },
    localized: {
      en: {
        title: "Locking Both Wings",
        prompt: "BLACK: Trade kingside pawns, then use the final pawn tempo to lock the queenside.",
        hint: "gxh6 gxh6 a4. After the kingside trade, ...a4 freezes both white pawns on a3 and b2 and leaves White with the unfavorable turn.",
      },
      ja: {
        title: "両翼の固定",
        prompt: "BLACK: キング側でポーンを交換し, 最後のポーンテンポでクイーン側を固定してください.",
        hint: "gxh6 gxh6 a4です. キング側の交換後に...a4で白のa3とb2のポーンを両方止め, 白を不利な手番に追い込みます.",
      },
    },
  },
  {
    id: "expert_084_reserve_tempo",
    title: "예비 템포의 힘",
    prompt: "WHITE: 폰 수를 아껴 두고 킹 대치에서 상대를 밀어내는 순서를 찾으세요.",
    hint: "g5 Ke7 f4 Kd7 Kf6 Kd6 Kg7입니다. g5와 f4를 차례로 두는 예비 템포가 흑 킹을 수동적으로 만들고 백 킹의 침투를 허용합니다.",
    fen: "8/5k1p/4p3/4K3/6P1/5P2/8/8 w - - 1 47",
    playerColor: "w",
    solutionSteps: [["g4g5"], ["f7e7"], ["f3f4"], ["e7d7"], ["e5f6"], ["d7d6"], ["f6g7"]],
    tags: ["advanced", "quietMove", "endgame", "pawnEndgame", "zugzwang"],
    source: { provider: "lichess", puzzleId: "0lgEc", rating: 2163 },
    localized: {
      en: {
        title: "The Power of Reserve Tempi",
        prompt: "WHITE: Preserve pawn moves and find the sequence that drives the opposing king back.",
        hint: "g5 Ke7 f4 Kd7 Kf6 Kd6 Kg7. The reserve tempi g5 and f4 leave Black passive and give the white king an entry route.",
      },
      ja: {
        title: "予備テンポの力",
        prompt: "WHITE: ポーンの手を温存し, キングの対峙で相手を後退させる順序を見つけてください.",
        hint: "g5 Ke7 f4 Kd7 Kf6 Kd6 Kg7です. g5とf4の予備テンポで黒キングを受け身にし, 白キングの侵入路を作ります.",
      },
    },
  },
  {
    id: "expert_085_opposition_lock",
    title: "폰으로 잠그는 오포지션",
    prompt: "BLACK: 서두르지 말고 퀸사이드를 고정한 뒤 킹으로 상대를 밀어내세요.",
    hint: "b6 Kd3 Kf3 Kd2 Kf2입니다. 조용한 ...b6이 백의 폰 돌파를 막고 킹 오포지션으로 결정적인 침투를 준비합니다.",
    fen: "8/1pp5/3p4/p2P4/P1PK1k2/2P5/8/8 b - - 3 42",
    playerColor: "b",
    solutionSteps: [["b7b6"], ["d4d3"], ["f4f3"], ["d3d2"], ["f3f2"]],
    tags: ["advanced", "defensiveMove", "quietMove", "endgame", "pawnEndgame", "zugzwang"],
    source: { provider: "lichess", puzzleId: "0PV2L", rating: 2414 },
    localized: {
      en: {
        title: "Locking in the Opposition",
        prompt: "BLACK: Fix the queenside without rushing, then use the king to force White back.",
        hint: "b6 Kd3 Kf3 Kd2 Kf2. The quiet ...b6 stops White's pawn break and preserves the winning king opposition.",
      },
      ja: {
        title: "ポーンで固定するオポジション",
        prompt: "BLACK: 急がずクイーン側を固定し, キングで相手を後退させてください.",
        hint: "b6 Kd3 Kf3 Kd2 Kf2です. 静かな...b6が白のポーンブレイクを止め, 勝てるキングのオポジションを保ちます.",
      },
    },
  },
  {
    id: "expert_086_knight_promotion_check",
    title: "체크를 위한 나이트 승급",
    prompt: "WHITE: 통과폰을 전진시킨 뒤 퀸이 아닌 기물로 승급해 템포를 얻으세요.",
    hint: "Rh7+ Kf6 dxe7 Rd1 e8=N+입니다. 나이트 언더프로모션만 f6의 킹을 즉시 체크해 흑 룩의 반격보다 한 템포 앞섭니다.",
    fen: "8/1p1rpk2/p2P3R/P1p5/4KP2/8/8/8 w - - 1 50",
    playerColor: "w",
    solutionSteps: [["h6h7"], ["f7f6"], ["d6e7"], ["d7d1"], ["e7e8n"]],
    tags: ["advanced", "advancedPawn", "endgame", "rookEndgame", "promotion", "underPromotion"],
    source: { provider: "lichess", puzzleId: "11fTg", rating: 2222 },
    localized: {
      en: {
        title: "Promote to a Knight with Check",
        prompt: "WHITE: Advance the passer, then promote to something other than a queen to gain a tempo.",
        hint: "Rh7+ Kf6 dxe7 Rd1 e8=N+. Only the knight underpromotion checks the king on f6 immediately and stays one tempo ahead of the rook.",
      },
      ja: {
        title: "チェックになるナイト昇格",
        prompt: "WHITE: パスポーンを進め, クイーン以外へ昇格してテンポを得てください.",
        hint: "Rh7+ Kf6 dxe7 Rd1 e8=N+です. ナイトへのアンダープロモーションだけがf6のキングへ直ちにチェックし, ルークの反撃より一手先を取れます.",
      },
    },
  },
  {
    id: "expert_087_race_with_check",
    title: "체크와 함께 끝나는 폰 레이스",
    prompt: "BLACK: 조용한 나이트 이동으로 정확한 폰 레이스를 시작하고 먼저 승급하세요.",
    hint: "Nb3 g5 a3 g6 a2 g7 a1=Q+입니다. ...Nb3은 g8에서 a2로 이어지는 비숍 대각선을 막고 a폰이 체크와 함께 승급하게 합니다.",
    fen: "6B1/8/5K2/8/pk1n2P1/3P2P1/8/8 b - - 1 45",
    playerColor: "b",
    solutionSteps: [["d4b3"], ["g4g5"], ["a4a3"], ["g5g6"], ["a3a2"], ["g6g7"], ["a2a1q"]],
    tags: ["advanced", "advancedPawn", "quietMove", "endgame", "promotion"],
    source: { provider: "lichess", puzzleId: "16hJT", rating: 1960 },
    localized: {
      en: {
        title: "A Pawn Race Ending in Check",
        prompt: "BLACK: Begin the exact pawn race with a quiet knight move and promote first.",
        hint: "Nb3 g5 a3 g6 a2 g7 a1=Q+. The non-checking ...Nb3 blocks the bishop's diagonal from g8 to a2 and lets the a-pawn promote with check.",
      },
      ja: {
        title: "チェックで終わるポーンレース",
        prompt: "BLACK: 静かなナイトの手から正確なポーンレースを始め, 先に昇格してください.",
        hint: "Nb3 g5 a3 g6 a2 g7 a1=Q+です. チェックではない...Nb3でg8からa2へのビショップの対角線を遮り, aポーンをチェック付きで昇格させます.",
      },
    },
  },
  {
    id: "expert_088_bishop_decoy_race",
    title: "비숍을 미끼로 한 승급",
    prompt: "BLACK: 비숍을 내주고 백 킹을 끌어내 통과폰의 승급 길을 여세요.",
    hint: "Ke5 Kxb4 c2 Kc3 c1=Q+입니다. 흑은 비숍을 미끼로 백 킹을 b4로 유인한 뒤 c폰을 막을 수 없는 승급 레이스로 보냅니다.",
    fen: "8/8/5k2/1K3Bp1/1b2P1P1/2p5/P7/8 b - - 0 60",
    playerColor: "b",
    solutionSteps: [["f6e5"], ["b5b4"], ["c3c2"], ["b4c3"], ["c2c1q"]],
    tags: ["advanced", "advancedPawn", "bishopEndgame", "endgame", "promotion", "sacrifice"],
    source: { provider: "lichess", puzzleId: "0TyX7", rating: 1986 },
    localized: {
      en: {
        title: "Bishop Decoy Promotion",
        prompt: "BLACK: Give up the bishop to draw the white king away and clear the passer's route.",
        hint: "Ke5 Kxb4 c2 Kc3 c1=Q+. Black offers the bishop to lure the king onto b4, then sends the c-pawn into an unstoppable promotion race.",
      },
      ja: {
        title: "ビショップを囮にする昇格",
        prompt: "BLACK: ビショップを渡して白キングを誘い出し, パスポーンの昇格路を開いてください.",
        hint: "Ke5 Kxb4 c2 Kc3 c1=Q+です. ビショップを囮にキングをb4へ誘い, cポーンを止められない昇格レースへ送ります.",
      },
    },
  },
  {
    id: "expert_089_lateral_rook_support",
    title: "통과폰을 위한 측면 지원",
    prompt: "BLACK: 룩으로 막고 있던 승급 파일을 비우고 옆에서 통과폰을 지원하세요.",
    hint: "Rb2 Ra4 a2 c6 Rb1+입니다. ...Rb2가 a2 칸을 비우면서 옆에서 a폰을 받치고 마지막 체크로 백 킹의 대응까지 제한합니다.",
    fen: "8/8/6pk/2P5/2R3P1/p7/r7/6K1 b - - 1 41",
    playerColor: "b",
    solutionSteps: [["a2b2"], ["c4a4"], ["a3a2"], ["c5c6"], ["b2b1"]],
    tags: ["advanced", "advancedPawn", "quietMove", "endgame", "rookEndgame"],
    source: { provider: "lichess", puzzleId: "0Smlf", rating: 2105 },
    localized: {
      en: {
        title: "Lateral Rook Support",
        prompt: "BLACK: Clear the promotion file with the rook and support the passed pawn from the side.",
        hint: "Rb2 Ra4 a2 c6 Rb1+. The move ...Rb2 clears a2, supports the a-pawn laterally, and finishes with a check that restricts the white king.",
      },
      ja: {
        title: "パスポーンへの横支援",
        prompt: "BLACK: ルークで塞いでいた昇格ファイルを空け, 横からパスポーンを支えてください.",
        hint: "Rb2 Ra4 a2 c6 Rb1+です. ...Rb2でa2を空けて横からaポーンを支え, 最後のチェックで白キングの応手も制限します.",
      },
    },
  },
  {
    id: "expert_090_rook_exchange_entry",
    title: "룩 교환 뒤 킹의 침투",
    prompt: "WHITE: 룩 교환을 강제해 상대 킹을 끌어낸 뒤 폰을 정리하고 침투하세요.",
    hint: "Rb8 Rc8 Rxc8 Kxc8 fxg4 Kd7 Kb7입니다. 룩 교환이 흑 킹을 c8로 유인하고 백 킹이 b7에 들어갈 결정적 템포를 만듭니다.",
    fen: "4r3/1RPk4/1K4p1/6p1/6p1/5P2/8/8 w - - 0 58",
    playerColor: "w",
    solutionSteps: [["b7b8"], ["e8c8"], ["b8c8"], ["d7c8"], ["f3g4"], ["c8d7"], ["b6b7"]],
    tags: ["advanced", "defensiveMove", "endgame", "rookEndgame", "zugzwang"],
    source: { provider: "lichess", puzzleId: "0uidm", rating: 2120 },
    localized: {
      en: {
        title: "King Entry After the Rook Trade",
        prompt: "WHITE: Force a rook trade, draw the enemy king away, then clear the pawn and penetrate.",
        hint: "Rb8 Rc8 Rxc8 Kxc8 fxg4 Kd7 Kb7. The rook trade draws Black's king to c8 and gives White the tempo needed to enter on b7.",
      },
      ja: {
        title: "ルーク交換後のキング侵入",
        prompt: "WHITE: ルーク交換を強制して相手キングを誘い, ポーンを取って侵入してください.",
        hint: "Rb8 Rc8 Rxc8 Kxc8 fxg4 Kd7 Kb7です. 交換で黒キングをc8へ誘い, 白キングがb7へ入る決定的なテンポを得ます.",
      },
    },
  },
  {
    id: "expert_091_defend_then_advance",
    title: "먼저 막고 나중에 전진",
    prompt: "WHITE: 룩 체크를 침착하게 피한 뒤 통과폰과 룩을 함께 활성화하세요.",
    hint: "Kf2 Rd3 d7 Kc3 Re3 Kd2 Rxd3+입니다. Kf2로 킹을 안전하게 둔 뒤 d폰을 전진시키고 Re3로 흑 킹의 접근을 끊어 룩을 되찾습니다.",
    fen: "8/8/3P4/p1p4p/1p1k4/1P2r3/4K3/4R3 w - - 5 42",
    playerColor: "w",
    solutionSteps: [["e2f2"], ["e3d3"], ["d6d7"], ["d4c3"], ["e1e3"], ["c3d2"], ["e3d3"]],
    tags: ["advanced", "advancedPawn", "defensiveMove", "endgame", "pin", "rookEndgame"],
    source: { provider: "lichess", puzzleId: "1DZs2", rating: 2135 },
    localized: {
      en: {
        title: "Defend First, Advance Later",
        prompt: "WHITE: Sidestep the rook check calmly, then activate the passer and rook together.",
        hint: "Kf2 Rd3 d7 Kc3 Re3 Kd2 Rxd3+. Kf2 secures the king, d7 advances the passer, and Re3 cuts off Black's king before the rook is recovered.",
      },
      ja: {
        title: "先に守ってから前進",
        prompt: "WHITE: ルークのチェックを落ち着いてかわし, パスポーンとルークを連動させてください.",
        hint: "Kf2 Rd3 d7 Kc3 Re3 Kd2 Rxd3+です. Kf2でキングを守り, d7で進め, Re3で黒キングを遮ってからルークを取り返します.",
      },
    },
  },
  {
    id: "expert_092_bishop_without_escape",
    title: "도망갈 칸이 없는 비숍",
    prompt: "BLACK: 급한 전술 대신 킹으로 갇힌 비숍에 접근해 안전하게 잡으세요.",
    hint: "Kd7 g4 Kc7 Kg3 Kxb7입니다. 비숍은 b7에서 퇴로가 없으므로 흑 킹은 폰 수에 흔들리지 않고 두 걸음으로 포획합니다.",
    fen: "8/1B2k3/8/r2p4/3Pp3/4P1P1/5PK1/8 b - - 6 84",
    playerColor: "b",
    solutionSteps: [["e7d7"], ["g3g4"], ["d7c7"], ["g2g3"], ["c7b7"]],
    tags: ["advanced", "endgame", "trappedPiece", "quietMove"],
    source: { provider: "lichess", puzzleId: "0AJz9", rating: 2044 },
    localized: {
      en: {
        title: "The Bishop Has No Escape",
        prompt: "BLACK: Ignore immediate tactics and walk the king toward the trapped bishop for a clean capture.",
        hint: "Kd7 g4 Kc7 Kg3 Kxb7. The bishop has no retreat from b7, so Black ignores the pawn moves and captures it in two king steps.",
      },
      ja: {
        title: "逃げ場のないビショップ",
        prompt: "BLACK: 急な戦術ではなく, キングで閉じ込められたビショップへ近づき確実に取ってください.",
        hint: "Kd7 g4 Kc7 Kg3 Kxb7です. b7のビショップには退路がなく, 黒キングはポーンの手に惑わされず二歩で取れます.",
      },
    },
  },
  {
    id: "expert_093_queen_corridor",
    title: "퀸을 몰아넣는 통로",
    prompt: "WHITE: 나이트로 흑 퀸의 선택지를 줄이고 룩을 이용해 강제 교환하세요.",
    hint: "Nc4 Qc3 Rc1 Qxc1 Qxc1입니다. Nc4가 퀸을 c3 통로로 몰고 Rc1이 퀸 교환을 강제해 갇힌 퀸의 활동을 끝냅니다.",
    fen: "rn4k1/6pp/p3pr2/8/1b6/8/Pq1N1PPP/R2Q1RK1 w - - 0 19",
    playerColor: "w",
    solutionSteps: [["d2c4"], ["b2c3"], ["a1c1"], ["c3c1"], ["d1c1"]],
    tags: ["advanced", "middlegame", "trappedPiece", "queenTrade", "quietMove"],
    source: { provider: "lichess", puzzleId: "0V54m", rating: 2385 },
    localized: {
      en: {
        title: "Herding the Queen into a Corridor",
        prompt: "WHITE: Restrict the black queen with the knight, then use the rook to force a queen trade.",
        hint: "Nc4 Qc3 Rc1 Qxc1 Qxc1. Nc4 drives the queen into the c3 corridor, and Rc1 forces the exchange that ends its trapped activity.",
      },
      ja: {
        title: "クイーンを追い込む通路",
        prompt: "WHITE: ナイトで黒クイーンの選択肢を減らし, ルークで強制的に交換してください.",
        hint: "Nc4 Qc3 Rc1 Qxc1 Qxc1です. Nc4でクイーンをc3の通路へ追い込み, Rc1で交換を強制して活動を終わらせます.",
      },
    },
  },
  {
    id: "expert_094_knight_route_to_queen",
    title: "퀸까지 이어지는 나이트 경로",
    prompt: "WHITE: 체크로 킹을 몰아낸 뒤 나이트의 경로를 바꿔 갇힌 퀸을 잡으세요.",
    hint: "Ne7+ Kb8 Nf5 Bxf6 Nxh4입니다. 나이트가 체크로 템포를 얻어 f5를 거쳐 h4의 퀸에 도달하고 비숍의 방해도 받아냅니다.",
    fen: "2kr2r1/ppp2p2/3p1P2/3Nn1bp/2P1Q1Pq/7P/PPP1R1K1/5R2 w - - 0 26",
    playerColor: "w",
    solutionSteps: [["d5e7"], ["c8b8"], ["e7f5"], ["g5f6"], ["f5h4"]],
    tags: ["advanced", "fork", "middlegame", "trappedPiece", "knightManeuver"],
    source: { provider: "lichess", puzzleId: "1C5kv", rating: 2189 },
    localized: {
      en: {
        title: "Knight Route to the Queen",
        prompt: "WHITE: Drive the king away with check, then reroute the knight to capture the trapped queen.",
        hint: "Ne7+ Kb8 Nf5 Bxf6 Nxh4. The knight gains a tempo by checking, reaches the queen on h4 through f5, and absorbs the bishop's interference.",
      },
      ja: {
        title: "クイーンへ続くナイトの経路",
        prompt: "WHITE: チェックでキングを追い, ナイトの経路を変えて閉じ込められたクイーンを取ってください.",
        hint: "Ne7+ Kb8 Nf5 Bxf6 Nxh4です. ナイトはチェックでテンポを得てf5経由でh4のクイーンへ届き, ビショップの妨害も受け止めます.",
      },
    },
  },
  {
    id: "expert_095_third_rank_rook_lift",
    title: "3랭크 룩 리프트",
    prompt: "WHITE: 직접 공격보다 룩을 3랭크로 올려 수비와 킹사이드 압박을 동시에 준비하세요.",
    hint: "Re3 Ne5 Rh3입니다. 조용한 Re3과 Rh3의 룩 리프트가 흑의 ...Ne5에 대응하면서 h파일의 퀸과 공격 진형을 만듭니다.",
    fen: "r4rk1/pp3p2/2n2p1Q/5q2/8/8/PP3PPP/3RR1K1 w - - 0 20",
    playerColor: "w",
    solutionSteps: [["e1e3"], ["c6e5"], ["e3h3"]],
    tags: ["advanced", "defensiveMove", "quietMove", "middlegame", "rookLift"],
    source: { provider: "lichess", puzzleId: "1AmCC", rating: 2116 },
    localized: {
      en: {
        title: "Third-Rank Rook Lift",
        prompt: "WHITE: Lift the rook to the third rank to combine defense with kingside pressure.",
        hint: "Re3 Ne5 Rh3. The quiet rook lift through e3 and h3 answers ...Ne5 while building an attacking formation with the queen on the h-file.",
      },
      ja: {
        title: "3段目のルークリフト",
        prompt: "WHITE: 直接攻めず, ルークを3段目へ上げて守備とキング側の圧力を両立してください.",
        hint: "Re3 Ne5 Rh3です. 静かなRe3からRh3へのルークリフトが...Ne5に対応し, hファイルのクイーンと攻撃陣形を作ります.",
      },
    },
  },
  {
    id: "expert_096_double_rook_battery",
    title: "조용한 더블 룩 배터리",
    prompt: "BLACK: 즉시 잡지 말고 두 룩을 한 파일에 겹쳐 강제 교환을 준비하세요.",
    hint: "Rgf6 Rf3 Rxf3 Nxf3 Rxf3입니다. ...Rgf6이 f파일에 룩을 겹쳐 백의 수비를 강제하고 두 차례 교환 뒤 흑 룩이 남습니다.",
    fen: "5r2/4k3/p1p1p1r1/PpPpb1p1/1P6/4P1R1/3B2R1/4N1K1 b - - 1 32",
    playerColor: "b",
    solutionSteps: [["g6f6"], ["g3f3"], ["f6f3"], ["e1f3"], ["f8f3"]],
    tags: ["advanced", "quietMove", "middlegame", "rookBattery", "exchangeSequence"],
    source: { provider: "lichess", puzzleId: "0P9M9", rating: 2321 },
    localized: {
      en: {
        title: "Quiet Double-Rook Battery",
        prompt: "BLACK: Do not capture immediately. Stack both rooks on one file and prepare a forced exchange.",
        hint: "Rgf6 Rf3 Rxf3 Nxf3 Rxf3. The quiet ...Rgf6 doubles on the f-file, forces White's defense, and leaves Black with the surviving rook after two exchanges.",
      },
      ja: {
        title: "静かなダブルルークの連携",
        prompt: "BLACK: すぐに取らず, 二つのルークを同じファイルへ重ねて強制交換を準備してください.",
        hint: "Rgf6 Rf3 Rxf3 Nxf3 Rxf3です. 静かな...Rgf6でfファイルにルークを重ね, 白の守備を強制して二度の交換後に黒ルークを残します.",
      },
    },
  },
  {
    id: "expert_097_lateral_rook_invasion",
    title: "옆으로 시작하는 룩 침투",
    prompt: "BLACK: 체크를 서두르지 말고 룩을 열린 가장자리로 옮겨 2랭크 침투를 준비하세요.",
    hint: "Ra8 Rd1 Ra2+ Nd2 Rxd2+ Rxd2 Qxd2+입니다. 조용한 ...Ra8이 a파일 침투를 예약하고 연속 체크와 교환으로 백 수비를 무너뜨립니다.",
    fen: "6r1/2Q1bk2/2p4P/2p1p3/2P1Nq2/3P1P2/5K2/7R b - - 0 37",
    playerColor: "b",
    solutionSteps: [["g8a8"], ["h1d1"], ["a8a2"], ["e4d2"], ["a2d2"], ["d1d2"], ["f4d2"]],
    tags: ["advanced", "quietMove", "endgame", "rookInvasion", "longSequence"],
    source: { provider: "lichess", puzzleId: "0gbeh", rating: 2048 },
    localized: {
      en: {
        title: "Lateral Rook Invasion",
        prompt: "BLACK: Delay the check, shift the rook to the open edge, and prepare a second-rank invasion.",
        hint: "Ra8 Rd1 Ra2+ Nd2 Rxd2+ Rxd2 Qxd2+. The quiet ...Ra8 reserves the a-file entry, then repeated checks and exchanges collapse White's defense.",
      },
      ja: {
        title: "横移動から始まるルーク侵入",
        prompt: "BLACK: チェックを急がず, ルークを開いた端へ移して2段目への侵入を準備してください.",
        hint: "Ra8 Rd1 Ra2+ Nd2 Rxd2+ Rxd2 Qxd2+です. 静かな...Ra8でaファイルへの侵入を予約し, 連続チェックと交換で白の守備を崩します.",
      },
    },
  },
  {
    id: "expert_098_outside_pawn_deflection",
    title: "바깥 통과폰의 디플렉션",
    prompt: "WHITE: 킹을 깊이 침투시킨 뒤 바깥 폰을 희생해 수비 폰을 끌어내세요.",
    hint: "Kc5 Kd7 Kb6 Kc8 a6 bxa6 Kxc6입니다. a폰 희생이 b폰을 a6으로 유인해 c6의 핵심 폰을 백 킹이 잡게 합니다.",
    fen: "8/1p6/2p1k1p1/P6p/1P1K3P/6P1/8/8 w - - 7 51",
    playerColor: "w",
    solutionSteps: [["d4c5"], ["e6d7"], ["c5b6"], ["d7c8"], ["a5a6"], ["b7a6"], ["b6c6"]],
    tags: ["advanced", "deflection", "endgame", "pawnEndgame", "outsidePassedPawn"],
    source: { provider: "lichess", puzzleId: "0GTDX", rating: 2029 },
    localized: {
      en: {
        title: "Outside Pawn Deflection",
        prompt: "WHITE: Penetrate with the king, then sacrifice the outside pawn to divert a defender.",
        hint: "Kc5 Kd7 Kb6 Kc8 a6 bxa6 Kxc6. The a-pawn sacrifice pulls the b-pawn onto a6 and lets the white king capture the key c6 pawn.",
      },
      ja: {
        title: "外側パスポーンのそらし",
        prompt: "WHITE: キングを深く侵入させ, 外側のポーンを犠牲にして守備ポーンを誘ってください.",
        hint: "Kc5 Kd7 Kb6 Kc8 a6 bxa6 Kxc6です. aポーンの犠牲でbポーンをa6へ誘い, 白キングが重要なc6ポーンを取れます.",
      },
    },
  },
  {
    id: "expert_099_center_pawn_race",
    title: "중앙 통과폰을 향한 킹",
    prompt: "BLACK: 퀸사이드 폰을 교환한 뒤 중앙 폰을 잡고 상대 통과폰 앞에 서세요.",
    hint: "bxc5 dxc5 Kxe5 c6 Kd6입니다. 교환으로 백 d폰을 c파일에 고정한 뒤 흑 킹이 e5 폰을 먹고 d6에서 승급을 봉쇄합니다.",
    fen: "8/8/1p2p1p1/p1P1P3/P2Pk3/8/5KP1/8 b - - 0 46",
    playerColor: "b",
    solutionSteps: [["b6c5"], ["d4c5"], ["e4e5"], ["c5c6"], ["e5d6"]],
    tags: ["advanced", "advancedPawn", "endgame", "pawnEndgame", "kingActivity"],
    source: { provider: "lichess", puzzleId: "0rRVb", rating: 2238 },
    localized: {
      en: {
        title: "King Against the Central Passer",
        prompt: "BLACK: Trade queenside pawns, capture in the center, and stand in front of White's passer.",
        hint: "bxc5 dxc5 Kxe5 c6 Kd6. The exchange fixes White's d-pawn on the c-file, then Black takes e5 and blocks promotion from d6.",
      },
      ja: {
        title: "中央パスポーンへ向かうキング",
        prompt: "BLACK: クイーン側で交換し, 中央のポーンを取って相手のパスポーンの前に立ってください.",
        hint: "bxc5 dxc5 Kxe5 c6 Kd6です. 交換で白のdポーンをcファイルに固定し, e5を取ってd6から昇格を止めます.",
      },
    },
  },
  {
    id: "expert_100_knight_clearance_promotion",
    title: "나이트 희생으로 여는 승급 길",
    prompt: "BLACK: 체크와 포크로 룩을 제거한 뒤 나이트를 희생해 e폰의 승급 칸을 여세요.",
    hint: "Nf3+ Kf5 Nxe1 Kxe4 Nd3 Kxd3 e1=Q입니다. 나이트가 룩을 잡고 d3에서 킹을 유인해 e폰의 직선 승급을 막을 기물을 없앱니다.",
    fen: "8/ppk5/2p5/6K1/2BPr2n/2P4P/PP2p3/4R3 b - - 0 41",
    playerColor: "b",
    solutionSteps: [["h4f3"], ["g5f5"], ["f3e1"], ["f5e4"], ["e1d3"], ["e4d3"], ["e2e1q"]],
    tags: ["advanced", "advancedPawn", "clearance", "endgame", "fork", "promotion"],
    source: { provider: "lichess", puzzleId: "0hxN2", rating: 2099 },
    localized: {
      en: {
        title: "Knight Clearance for Promotion",
        prompt: "BLACK: Remove the rook with a checking fork, then sacrifice the knight to clear the e-pawn's route.",
        hint: "Nf3+ Kf5 Nxe1 Kxe4 Nd3 Kxd3 e1=Q. The knight wins the rook and lures the king onto d3, removing the last obstacle to the e-pawn's promotion.",
      },
      ja: {
        title: "ナイト犠牲で開く昇格路",
        prompt: "BLACK: チェックとフォークでルークを除き, ナイトを犠牲にしてeポーンの昇格路を開いてください.",
        hint: "Nf3+ Kf5 Nxe1 Kxe4 Nd3 Kxd3 e1=Qです. ナイトがルークを取り, d3へキングを誘ってeポーン昇格の最後の障害を除きます.",
      },
    },
  },
];
